### ISSUE TITLE
Send submissions retroactively

### ISSUE THREAD

**Issue by pavelsokolov** [danmarsden/moodle-plagiarism_urkund#100]
Hi,

Right now it feels that the files submitted prior to Urkund being enable for the assignment, are not sent to the plagiarism check. Would it be possible to make Urkund handle it retroactively? So e.g. a scheduled task check for all file submissions for that assignment, and not only look through {plagiarism_urkund_files}

**Comment by danmarsden** [comment]
Hi there - the issue with this in the past has been that students do not receive any disclosure statement prior to the file being uploaded. From what I understand in some jurisdictions this may be problematic. I don't think it would be wise to automatically upload any prior submissions but it might be possible to have an admin tool that allowed you to select a specific assignment and upload all previous submissions. (with appropriate warnings displayed to the teacher/admin around policy/potential legal issues etc)

**Comment by danmarsden** [comment]
I'm closing this as "won't fix" for now, but feel free to talk with Urkund directly about this further and they may decide to fund improvements around this functionality.
