### ISSUE TITLE
Moodle 3.0 with forums and workshop: blank error

### ISSUE THREAD

**Issue by jpahullo** [danmarsden/moodle-plagiarism_urkund#106]
We have detected on production, in our Moodle 3.0, that when upgrading to the last version of this plugin (branch MOODLE_30_STABLE) there is an error that prevents professors editing settings from forums and workshop when enabling Urkund.

## Error description

1. Error context: management of advanced settings.
1. Error line: lib.php:529.
1. Reason: tries to remove the setting `urkund_draft_submit` when it is not available on forums and workshops.

## Solution proposal

1. Updating to hidden elements only existing elements in the current form from the default settings.

We are working on this patch. Maybe it is also aplicable to other upper versions.

**Comment by danmarsden** [comment]
Thanks for the report and patch! - I have merged that into all versions.

**Comment by jpahullo** [comment]
Ok! Thank you very much @danmarsden !!

We're going to apply it in our Moodle too.

Thanks a lot.

Jordi

**Comment by jpahullo** [comment]
Hi again,

When I did `git remote update` I saw updating of all branches except `MOODLE_31_STABLE`. Is that ok?

Thanks!

Jordi

**Comment by jpahullo** [comment]
Now I see that there is not such a MOODLE_31_STABLE branch, so all ok.

Thank you for the job!

Jordi
