### ISSUE TITLE
Emails are sent out to students, but the option is disabled

### ISSUE THREAD

**Issue by adpe** [danmarsden/moodle-plagiarism_urkund#116]
Hello @danmarsden 

We're encountering following problem using the recent version of the plugin with Moodle 3.5.5+ (Build: 20190311).

The option `Send student email` is set to `No`. But unfortunately the students receives the _Confirmation of receipt_. In the general settings I've disabled the `Show opt-out link` setting.

Can you help me?

Thanks
Adrian

**Comment by danmarsden** [comment]
Hi Adrian, 

You should ask your Urkund support contact about this - it sounds like the notifications you want to disable are the ones that come directly from urkund, rather than the notifications sent from Moodle. I believe they can turn these off at a global level on your account.
