### ISSUE TITLE
Error messages when email is globally disabled

### ISSUE THREAD

**Issue by moleculech** [danmarsden/moodle-plagiarism_urkund#117]
Hi
On our dev server we've disabled all email delivery. When we upload a new file to urkund the following message appears:

```
line 5815 of /lib/moodlelib.php: call to debugging()
line 94 of /message/output/email/message_output_email.php: call to email_to_user()
line 150 of /lib/classes/message/manager.php: call to message_output_email->send_message()
line 112 of /lib/classes/message/manager.php: call to core\message\manager::send_message_to_processors()
line 296 of /lib/messagelib.php: call to core\message\manager::send_message()
line 6065 of /mod/assign/locallib.php: call to message_send()
line 6093 of /mod/assign/locallib.php: call to assign::send_assignment_notification()
line 6186 of /mod/assign/locallib.php: call to assign->send_notification()
line 7140 of /mod/assign/locallib.php: call to assign->notify_graders()
line 7176 of /mod/assign/locallib.php: call to assign->save_submission()
line 456 of /mod/assign/locallib.php: call to assign->process_save_submission()
line 55 of /mod/assign/view.php: call to assign->view()
Not sending email due to $CFG->noemailever config setting
```

It is not a big issue, since the upload still works. Unfortunately Beta-Testers will be confused. Can you implement some kind of catching fo this problem?

Thank you very much.
Cheers

**Comment by danmarsden** [comment]
Hi there, that's a standard debug error that comes from the moodle core codebase when email is disabled and developer debugging is enabled. It has nothing to do with urkund code and would display even if you removed the urkund code. Thanks.

**Comment by moleculech** [comment]
Hi, thanks for your answer. 
In my opinion one should be allowed to dissable e-mail delivery (Without receiving error messages). I will open the issue directly with moodle.
Have a nice day.

**Comment by danmarsden** [comment]
You can by decreasing the debugging level in your site.
