### ISSUE TITLE
Urkund plugin suggests support for any module that declares FEATURE_PLAGIARISM

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#118]
We installed the Coursework module (https://docs.moodle.org/37/en/Coursework_module). The urkund plugin now shows an option to enable Urkund for it. I'm pretty sure Urkund doesn't support it. 

The reason seems to be that it simply shows an enabled option for any module that advertises FEATURE_PLAGIARISM. In this case, the only support being provided by Turnitin

**Comment by danmarsden** [comment]
Thanks @thepurpleblob - sounds like we should probably look at adding support for the coursework module. It's not normally all that difficult to support extra activity plugins.

**Comment by danmarsden** [comment]
hmm - although I see it hasn't really been updated since the 3.4 release and it's not listed in the plugins db so if it's not maintained well it might just be worth ignoring coursework for now.

**Comment by danmarsden** [comment]
dropped a fix for this into the git branch - I didn't think it was worth pushing this out on it's own to the plugins db, but let me know if you want me to drop a new release into the plugins db with this change.

**Comment by thepurpleblob** [comment]
It's fine - thanks - it didn't really bother me. I just saw the tick box and was surprised :)

Interestingly, my colleague @lexxkoto wrote some patches last year to get the Urkund plugin working with Coursework. We had it all working a site but interest fizzled out a bit. 

If you want, I can get him involved and maybe test on the latest version and send a pull request?

**Comment by danmarsden** [comment]
If you have someone actively using coursework - and is likely to continue using it .... and you have some patches already done then go for it - the urkund plugin also includes support for the hsuforum as well. But if the interest fizzled out I'm less inclined to drop it in because coursework doesn't appear to be actively maintained at the moment?
