### ISSUE TITLE
Class 'plagiarism_urkund\event\base' not found

### ISSUE THREAD

**Issue by dsbellcom** [danmarsden/moodle-plagiarism_urkund#119]
When I use admin/tool/brcli/restore.php to restore courses, I got this error for some courses:

> Default exception handler: Erand: Class 'plagiarism_urkund\event\base' not found Debug:
> Error code: generalexceptionmessage
> * line 88 of /plagiarism/urkund/classes/event/assessment_resubmitted.php: Error thrown
> * line 101 of /admin/tool/log/backup/moodle2/restore_tool_log_logstore_subplugin.class.php: call to plagiarism_urkund\event\assessment_resubmitted::get_objectid_mapping()
> * line 63 of /admin/tool/log/store/standard/backup/moodle2/restore_logstore_standard_subplugin.class.php: call to restore_tool_log_logstore_subplugin->process_log()
> * line 137 of /backup/util/plan/restore_structure_step.class.php: call to restore_logstore_standard_subplugin->process_logstore_standard_log()
> * line 112 of /backup/util/helper/restore_structure_parser_processor.class.php: call to restore_structure_step->process()
> * line 178 of /backup/util/xml/parser/processors/grouped_parser_processor.class.php: call to restore_structure_parser_processor->dispatch_chunk()
> * line 100 of /backup/util/helper/restore_structure_parser_processor.class.php: call to grouped_parser_processor->postprocess_chunk()
> * line 148 of /backup/util/xml/parser/processors/simplified_parser_processor.class.php: call to restore_structure_parser_processor->postprocess_chunk()
> * line 92 of /backup/util/xml/parser/processors/progressive_parser_processor.class.php: call to simplified_parser_processor->process_chunk()
> * line 190 of /backup/util/xml/parser/progressive_parser.class.php: call to progressive_parser_processor->receive_chunk()
> * line 278 of /backup/util/xml/parser/progressive_parser.class.php: call to progressive_parser->publish()
> * line ? of unknownfile: call to progressive_parser->end_tag()
> * line 179 of /backup/util/xml/parser/progressive_parser.class.php: call to xml_parse()
> * line 158 of /backup/util/xml/parser/progressive_parser.class.php: call to progressive_parser->parse()
> * line 110 of /backup/util/plan/restore_structure_step.class.php: call to progressive_parser->process()
> * line 181 of /backup/util/plan/base_task.class.php: call to restore_structure_step->execute()
> * line 210 of /backup/moodle2/restore_activity_task.class.php: call to base_task->execute()
> * line 178 of /backup/util/plan/base_plan.class.php: call to restore_activity_task->execute()
> * line 168 of /backup/util/plan/restore_plan.class.php: call to base_plan->execute()
> * line 354 of /backup/controller/restore_controller.class.php: call to restore_plan->execute()
> * line 81 of /admin/tool/brcli/restore.php: call to restore_controller->execute_plan()
> 
> !!! Erand: Class 'plagiarism_urkund\event\base' not found !!!
> Potential coding error - existing temptables found when disposing database. Must be dropped!
> 

Seems there is a bug on /plagiarism/urkund/classes/event/assessment_resubmitted.php
Need to change line nr. 88 from
`        return base::NOT_MAPPED;`
to 
`        return self::NOT_MAPPED;`

**Comment by danmarsden** [comment]
thanks for the report! - I've just pushed though a fix into github here that should sort that.
