### ISSUE TITLE
Student submissions via Moodle result in 0 word(s) documents in Urkund

### ISSUE THREAD

**Issue by crazycyke** [danmarsden/moodle-plagiarism_urkund#120]
We have multiple campus within Moodle.
A few weeks ago, all student submissions to Moodle result in a 0 byte (0 word(s)) document being submitted to Urkund.

If you use the 'reset' link under the Debug page then the file is resubmitted correctly and can be evaluated (i.e. no problems).

The hardware / environment is the same as it will work on one campus but not the other.

Are there any suggestions about what to look for?

Thanks,
Craig.

**Comment by danmarsden** [comment]
the reset process uses the same code path for sending the files as the automatic process, so I assume this isn't an ongoing issue and only related to file submissions that were sent in a particular timeframe?

The code uses Curl calls directly from your server to Urkund - so something between your server and urkund probably stripped out the file content - maybe a web proxy or firewall - or possibly even an urkund system outage that occurred at the time? - I don't think I can help further here - if you need further help with diagnosing this, you might want to contract your local Moodle partner to investigate further.

good luck!
