### ISSUE TITLE
Enable Urkund on third party plugins

### ISSUE THREAD

**Issue by ferranrecio** [danmarsden/moodle-plagiarism_urkund#122]
Hello Dan,

First of all, thanks a lot for your plugin. We are using at the Universitat Politècnica de Catalunya for some time and it works great.

We have a custom activitty in our campus called "Final Thesis" (special for uploading PhD thesis). We found that activating the plugin plagiarism on the Urkund global settings (urkund_enable_mod_final_thesis) does not work.

In order to use Urkund for modules other than workshop, assign, forum and hsuforum we had to modify some hard-coded arrays in the "urkund_supported_modules" function and add some code at the end of the function "plagiarism_urkund_get_file_object" to create a generic file case .

```php
        $result = $DB->get_record_select('files', 'contenthash = ? AND filearea <> ? AND contextid = ?', array($plagiarismfile->identifier, 'draft', $modulecontext->id));
        if ($result) {
            $file = $fs->get_file_instance($result);
            if (debugging()) {
                mtrace("URKUND fileid:" . $plagiarismfile->id . " found fileid:" . $file->get_id());
            }
            return $file;
        }
```
If you want we can make a pull request of our changes to test it.

Is it possible to add something similar for all non standard plugins?

**Comment by danmarsden** [comment]
Hey! - Pull requests always welcome :-)

could be handy to have a var you could set at config.php like:
$CFG->forced_plugin_settings = array('plagiarism_urkund'  => array('extraplugins' => 'mod_finalthesis;'),

And then something that loops over all those extra plugins in the relevant places. but in your code example that file case looking for filearea='draft' looks very strange... - would be better if that could be looking for filearea = "mod_finalthesis" or whatever your plugin name is called - does that make sense?

thanks!

**Comment by ferranrecio** [comment]
Hi,

We will do a pull request as soon as we can, thanks.

The case we implement is looking for fileare different than 'draft', not equal (ignoring draft files). We think this is the most standard way of doing it but of course it could be other options.

**Comment by danmarsden** [comment]
My first impression is that feels wrong, and it should be explicit about requesting files related to the enabled plugin in a known filearea - but if you don't find a nice way of doing that file the pull request and I'll take a look!

**Comment by danmarsden** [comment]
closing this one for now, but feel free to submit a PR with a change for me to look closer.
