### ISSUE TITLE
Advanced settings none option missing

### ISSUE THREAD

**Issue by gonedjur** [danmarsden/moodle-plagiarism_urkund#125]
When selecting and advanced option you don't have the ability to deselect it to "None" after having made a selection in the dropdown. Is this by design?

**Comment by danmarsden** [comment]
it's a multi-select box - not a great UX but it's very quick to implement for the developer - this fucntionality was developed externally and submitted as a pull reuqest.

For windows: Hold down the control (ctrl) button to select/deselect multiple options
For Mac: Hold down the command button to select/deselect multiple options
