### ISSUE TITLE
Remove element form

### ISSUE THREAD

**Issue by darioroig** [danmarsden/moodle-plagiarism_urkund#135]
The element urkund_resubmit_on_close only belong to mod_assign, the code always try remove  the element. If you edit any activity with debug activate show a error page.

To solve the bug, you need add this patch in Urkund/lib.php:
//DRG URKUND parche. Solo debe entra aqui si es mod_assing.
            if ($modulename == 'mod_assign' ) {
             if (!has_capability('plagiarism/urkund:resubmitonclose', $context)) {
                $mform->removeElement('urkund_resubmit_on_close');
             }
            }

**Comment by danmarsden** [comment]
Thanks for the report! - I haven't seen this before so it would be good to know what Moodle version you are using so I can reproduce this as well.

thanks!

**Comment by darioroig** [comment]
Hi! Thanks to answer. 
The bug you can reproduce in the following versions:
-Moodle 3.7.4 or Moodle 3.8.1
-Urkund 3.8.1
Regards

**Comment by danmarsden** [comment]
Thanks - I'll get a patch into the latest release very soon.
Btw - the latest "master" branch here has a lot of recent improvements/changes that haven't been released in the moodle plugins db yet - let us know if you have any other issues!

thanks,
