### ISSUE TITLE
Last version (3.8.9) is not compatible with Moodle 3.6

### ISSUE THREAD

**Issue by carlosalal** [danmarsden/moodle-plagiarism_urkund#145]
the file urkund_debug.php references to 'core\output\checkbox_toggleall', this component is not available on versions lower than 3.8.

**Comment by danmarsden** [comment]
Thanks for the report! - I've removed that and published an updated version for older releases that fixes this.

Interesting to see you mention 3.6 though - support for security fixes in 3.6 ended 8 months ago - you really need to upgrade your site asap.

Typically we drop support for Moodle versions at the same time Moodle does but that particular branch supports Moodle 3.5 which is still a supported release (but only for the next 4 months) - when 3.5 goes out of support we will no longer be making changes to branches older than 3.9
