### ISSUE TITLE
Deprecated function.

### ISSUE THREAD

**Issue by OscarNadjar** [danmarsden/moodle-plagiarism_urkund#149]
Hi, I work for the Open LMS team and we found an issue about a deprecated function on the plugin. 
plagiarism/urkund/lib.php line 978:
array_key_exists('use_urkund', $data) -> array_key_exists() is deprecated on PHP. 7.4 for objects, it can be change to ->
property_exists($data,'use_urkund')

**Comment by danmarsden** [comment]
@OscarNadjar - what version of Moodle and what version of this plugin are you using?

The Main branch here (which supports current supported releases of Moodle (3.9 and higher) supports PHP 7.4 and doesn't throw any deprecated warnings.

It's possible that the older branches for unsupported Moodle versions might still throw this error, pull requests are always welcome.

**Comment by danmarsden** [comment]
closing due to lack of response and all supported branches should support php 7.4
