### ISSUE TITLE
breaking backward behaviour on advanced settings

### ISSUE THREAD

**Issue by jpahullo** [danmarsden/moodle-plagiarism_urkund#150]
On #109 we contributed the possibility to hide Urkund settings to teachers, by defining them in the plugin settings as advanced.

On the last version available for Moodle 3.10, the plugin version 3.9.18 (2021081801), it seems that this is broken.

More specifically:

1. Adding an activity with urkund support, the activity form hides the fields properly.
2. When editing an activity with urkund support, all Urkund fields are shown. This is not expected.

When submitting that #109, either when adding or editing an activity with urkund support, the selected settings where properly hidden.

**Comment by danmarsden** [comment]
@jpahullo did I need to come back to this? - or was it not an issue in the end?

**Comment by jpahullo** [comment]
Hi! It was an issue in code, a codition within the form. Let me check it (we applied a local patch) and make a PR for it for you to ease solve it. I'll be back in a while.

**Comment by jpahullo** [comment]
Well, you solve it with #151, that I already made. It was the same issue. Sorry for duplicating it. Thank you a lot for your time and work.

**Comment by danmarsden** [comment]
Great thanks!
