### ISSUE TITLE
Multilang in submission information

### ISSUE THREAD

**Issue by cdipe** [danmarsden/moodle-plagiarism_urkund#152]
There should be support for multiple languages for the submission information. The easiest would probably be to add this to the language pack instead.
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/14754240/154970469-1e9f9b9c-6542-4aee-b559-1948241471de.png">

**Comment by danmarsden** [comment]
This field supports Moodle's standard Multi-language content feature which is the right way to achieve this but still allow the site admin to easily change the policy please see:
https://docs.moodle.org/en/Multi-language_content_filter

thanks!

**Comment by cdipe** [comment]
@danmarsden thank you, works perfectly! 
(I kick myself for not trying that... I thought it removed all html, since I tried making some words bold and that was removed.)
