### ISSUE TITLE
There is a malformed field value in a query used by the `plagiarism_urkund_get_file_object` method

### ISSUE THREAD

**Issue by Undreli-Studios** [danmarsden/moodle-plagiarism_urkund#154]
Good day, in the `lib.php` file there is a method called `plagiarism_urkund_get_file_object`, which uses a query that has a non-existent field, that looks to be malformed.

You can find it here: https://github.com/danmarsden/moodle-plagiarism_urkund/blob/MOODLE_400_STABLE/lib.php#L2017

The specific code reads `$sql = "SELECT a.id, o.one73fe0fff330c5ce6718df3d9440bf9bd6316623linetext`, but the `o.one73fe0fff330c5ce6718df3d9440bf9bd6316623linetext` field doesn't exist in the `assignsubmission_onlinetext` table (the appropriate field might be `o.onlinetext`). The tests from this plugin pass, which possibly indicates that the `plagiarism_urkund_get_file_object` method doesn't have coverage where it executes this query. It would be great if a test could be added to cover this scenario to verify this method works as expected.

Thank you very much for your attention.

**Comment by danmarsden** [comment]
whoops - thanks for the report - not sure how that snuck in there - now that Turnitin owns Ouriginal I'm not sure they're willing to fund further improvements to this plugin (adding more unit tests etc) but I've fixed that typo and will push a version to the plugins db with the update.

thanks again!
