### ISSUE TITLE
intervals in urkund_check_attempt_timeout

### ISSUE THREAD

**Issue by schach** [danmarsden/moodle-plagiarism_urkund#26]
Hi Dan.

Had a look into moodle-plagiarism_urkund lib.php's urkund_check_attempt_timeout -function to see what kind of intervals it produces.
It seems to behave differently to what is described in the comments: Initial delay, doubled each time a check is made until the max_status_delay is met.

In case of submissions it is (in minutes):
$plagiarismfile->attempt: 0, $wait: 15
$plagiarismfile->attempt: 1, $wait: 15
$plagiarismfile->attempt: 2, $wait: 60
$plagiarismfile->attempt: 3, $wait: 180
$plagiarismfile->attempt: 4, $wait: 240
$plagiarismfile->attempt: 5, $wait: 300

... and for status (in minutes):
$plagiarismfile->attempt: 0, $wait: 30
$plagiarismfile->attempt: 1, $wait: 30
$plagiarismfile->attempt: 2, $wait: 120
$plagiarismfile->attempt: 3, $wait: 810
$plagiarismfile->attempt: 4, $wait: 5760
$plagiarismfile->attempt: 5, $wait: 7200
$plagiarismfile->attempt: 6, $wait: 8640
$plagiarismfile->attempt: 7, $wait: 10080
$plagiarismfile->attempt: 8, $wait: 11520
$plagiarismfile->attempt: 9, $wait: 12960

Notice the interval between attempt 3 and 4.

**Comment by danmarsden** [comment]
patch was merged - closing this one off, thanks!
