### ISSUE TITLE
Type settings needed for urkund_get_form_elements() in lib.php

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#28]
Currently (with debugging on) throws...

Did you remember to call setType() for 'use_urkund'? Defaulting to PARAM_RAW cleaning.
line 1312 of /lib/formslib.php: call to debugging()
line 284 of /lib/formslib.php: call to moodleform->detectMissingSetType()
line 202 of /lib/formslib.php: call to moodleform->_process_submission()
line 86 of /course/moodleform_mod.php: call to moodleform->moodleform()
line 254 of /course/modedit.php: call to moodleform_mod->moodleform_mod()
Did you remember to call setType() for 'urkund_show_student_score'? Defaulting to PARAM_RAW cleaning.
line 1312 of /lib/formslib.php: call to debugging()
line 284 of /lib/formslib.php: call to moodleform->detectMissingSetType()
line 202 of /lib/formslib.php: call to moodleform->_process_submission()
line 86 of /course/moodleform_mod.php: call to moodleform->moodleform()
line 254 of /course/modedit.php: call to moodleform_mod->moodleform_mod()
Did you remember to call setType() for 'urkund_show_student_report'? Defaulting to PARAM_RAW cleaning.
line 1312 of /lib/formslib.php: call to debugging()
line 284 of /lib/formslib.php: call to moodleform->detectMissingSetType()
line 202 of /lib/formslib.php: call to moodleform->_process_submission()
line 86 of /course/moodleform_mod.php: call to moodleform->moodleform()
line 254 of /course/modedit.php: call to moodleform_mod->moodleform_mod()
Did you remember to call setType() for 'urkund_draft_submit'? Defaulting to PARAM_RAW cleaning.
line 1312 of /lib/formslib.php: call to debugging()
line 284 of /lib/formslib.php: call to moodleform->detectMissingSetType()
line 202 of /lib/formslib.php: call to moodleform->_process_submission()
line 86 of /course/moodleform_mod.php: call to moodleform->moodleform()
line 254 of /course/modedit.php: call to moodleform_mod->moodleform_mod()
Did you remember to call setType() for 'urkund_receiver'? Defaulting to PARAM_RAW cleaning.
line 1312 of /lib/formslib.php: call to debugging()
line 284 of /lib/formslib.php: call to moodleform->detectMissingSetType()
line 202 of /lib/formslib.php: call to moodleform->_process_submission()
line 86 of /course/moodleform_mod.php: call to moodleform->moodleform()
line 254 of /course/modedit.php: call to moodleform_mod->moodleform_mod()
Did you remember to call setType() for 'urkund_studentemail'? Defaulting to PARAM_RAW cleaning.
line 1312 of /lib/formslib.php: call to debugging()
line 284 of /lib/formslib.php: call to moodleform->detectMissingSetType()
line 202 of /lib/formslib.php: call to moodleform->_process_submission()
line 86 of /course/moodleform_mod.php: call to moodleform->moodleform()
line 254 of /course/modedit.php: call to moodleform_mod->moodleform_mod()

**Comment by thepurpleblob** [comment]
I'm not sure why, but these notices are only thrown under the same conditions as https://github.com/danmarsden/moodle-plagiarism_urkund/issues/29 (i.e. when the capability to enable Urkund is withdrawn)

**Comment by danmarsden** [comment]
Thanks Howard, I've just pushed a patch that should fix that. Let me know if it all works as expected!

**Comment by danmarsden** [comment]
version including this patch has been released to the plugins db
