### ISSUE TITLE
Switching off plagiarism/urkund:enable capability breaks Assignment settings page

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#29]
To reproduce...
1. Create a course and a user. Add the user to the course as a teacher
2. Modify the Teacher role so that plagiarism/urkund:enable is NOT allowed
3. Log into Moodle as the user and go to the course
4. Create a new assignment

- On the setting page, go to 'Restrictions' and open it. Note that this should be a javascript popup but only a textarea box is displayed. If you run the Javascript Console you will see that a javascript error is thrown...

![screen shot 2015-01-16 at 15 07 09](https://cloud.githubusercontent.com/assets/664139/5778969/f7e1db58-9d96-11e4-92c2-2ce39f1fab53.png)

The Urkund error seems to be stopping the rest of the javascript on the page. If a user inadvertently types something into that box then they'll get a JSON error and it won't save (this is actually an assignment bug-ette I suppose). 

We found this because we wanted to restrict the use of Urkund to certain users for a pilot study.

**Comment by thepurpleblob** [comment]
The problem is that the capability is not checked when checkreceiver.js is loaded. It's loaded regardless and is not needed. I'll submit a patch if I get a chance.

**Comment by thepurpleblob** [comment]
https://github.com/danmarsden/moodle-plagiarism_urkund/pull/30

**Comment by danmarsden** [comment]
Thanks Howard - I've merged those changes in - thanks for tracking it down!
