### ISSUE TITLE
Have option to only process file on final submit

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#31]
At the moment the file is sent for scoring every time a the file is uploaded into assignment. There's effectively no limit on this and a student can keep uploading their paper until they get a suitably low score - then submitting for grading. 

It would be very nice to have an (instance) option that only submitted to Urkund when the paper was finally submitted for grading. Some academics are keen that they only get one shot at receiving a plagiarism score.

**Comment by danmarsden** [comment]
There is supposed to be an option for that when using the assignment plugin - "urkund_draft_submit" it's possible that it isn't being shown in the form due to changes to the assignment plugin though. Or are you referring to other activities?

see: https://github.com/danmarsden/moodle-plagiarism_urkund/blob/master/lib.php#L819

"var4" was for assignment 2.2 and older - "submissiondrafts" was for newer versions of assignment when drafts were used.

**Comment by thepurpleblob** [comment]
I don't recall seeing anything like that. Yes, I'm talking about Assignment (we only use it for Assignment, I forget there are other options!).

I'll go and have a dig around later on now I know what I'm looking for.

**Comment by danmarsden** [comment]
I just took a quick look and the setting still shows and enables/disables correctly when draftsubmission settings are used within the assignment (Require students click submit button) - it could be there's another issue somewhere though.

**Comment by thepurpleblob** [comment]
Yes - we tried that. We set the thing up to 'submit file when students send for marking' and also forced them to press the 'submit' button. The result was that the file never got sent to Urkund. Unfortunately, we tried to replicate this on a test box and that appeared to work as expected. So, we're a bit confused about what is going on. Are there any other conditions for sending a file only when the submission is 'finalised' that we might have missed?

**Comment by thepurpleblob** [comment]
See - https://github.com/danmarsden/moodle-plagiarism_urkund/issues/37

**Comment by thepurpleblob** [comment]
Between getting the settings right and the fix for #37, this can now be closed.

**Comment by danmarsden** [comment]
cool - thanks!

**Comment by thepurpleblob** [comment]
Hi,
I know you were looking for this, I found this stuff for you, take a look at <http://assist.gayathra.com/e4kksi>

My Best, howard@e-learndesign.co.uk
