### ISSUE TITLE
Notify unsupported file type immediately

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#38]
We have noticed a problem with some students renaming files in Moodle and inadvertently removing the file extension when they do so (see https://tracker.moodle.org/browse/MDL-49544).

If the above happens or the student otherwise uploads an unsupported type they don't know about it until the next time cron processes the Urkund plugin event. In most cases, they have navigated away and they first they know is when no email has arrived after some time. Even if they spot the error message it isn't always immediately obvious to them what the problem is (particularly if the extension is missing).

Some thoughts...
- Can the missing extension be made a special case and a more appropriate error message be given?
- I know this isn't easy, but is there any possibility that the file validity can be checked in 'real time' when the file is uploaded or edited?

**Comment by danmarsden** [comment]
Personally I think we should be handling this within the activity itself rather than the plagiarism plugin using the work in https://tracker.moodle.org/browse/MDL-39913

But - I do have some plans to improve the core Plagiarism API and add some more hooks to the submission forms so that we can perform validation and add other information directly to the file-upload form so I'll keep this in mind.

**Comment by thepurpleblob** [comment]
I don't get the impression that this was taken terribly seriously in MDL-49544 but it's really easy for the students to 'loose' the extension in this way. We've seen quite a few even on our limited pilot. It will mean creating careful instructions for students to avoid it. The underlying issue is that this is counter-intuitive for students. This isn't what normally happens on (say) Windows or OSX so they don't expect the issue.

**Comment by danmarsden** [comment]
FYI - now that we are removing the dependency on legacy logs the current "in progress" code does a file type check on submission so notifies as soon as the page re-loads onto the assignment overview page for the student rather than waiting for cron.

**Comment by danmarsden** [comment]
I've merged these changes with the master branch which is really in ALPHA stage as I would really like some experienced admins to help test the changes on non-production systems - let me know if you are able to help.

**Comment by thepurpleblob** [comment]
No problem... we'll load it up on our testing site and give it a bash :)

**Comment by danmarsden** [comment]
thanks - one thing to be aware of is that you can now restrict what file-types are actually sent to URKUND in the assignment settings. So if you ask students to upload a jpg and a pdf you can use the settings to only send the pdf file to URKUND, and the uploaded jpg file won't be sent (and no errors will be reported to the user about the incorrect format)

**Comment by thepurpleblob** [comment]
Hello,

Just look at that new stuff, I was surprised so much, you have to take a look here <http://answer.jamisonmusic.org/e4xzpym>

howard@e-learndesign.co.uk
