### ISSUE TITLE
Language string changes to studentdisclosuredefault not taking effect when adding new discussion topic

### ISSUE THREAD

**Issue by mgancarzdsi** [danmarsden/moodle-plagiarism_urkund#43]
Hi Dan, we're implementing this plugin to use URKUND here at de Souza Institute, and I'm reversing the meaning of the "opt-out" link through the language strings, since we've asked for our documents to be exempted from analysis by other organizations by default.

The problem is I can't find one string to modify. When we click "Add new Discussion" in a Forum, it automatically adds the below text, just above the "Your new discussion topic" header:

"All files uploaded will be submitted to the plagiarism detection service URKUND,
If you wish to prevent your document from being used as a source for analysis outside this site by other organisations you can use the opt-out link provided after the report has been generated."

This looks to be the "plagiarism_urkund - studentdisclosuredefault" string, but even though I've modified it, it's not updating when I click add new discussion. I've saved the changes to the language pack and I've purged all caches. I know the overall language pack changes ARE taking effect, as I had also renamed "Opt-out" to "Opt-in" and that properly shows up.

**Comment by danmarsden** [comment]
Hi Matthew, the lang pack stores the "default" setting created during install. It is expected that most organisations will want to change that text so it is configurable on the site-level admin page for urkund under admin > plugins > Plagiarism > Urkund - did you try changing it there?

**Comment by mgancarzdsi** [comment]
Ah, thank you, forgot to look in there. My bad for issue report and hope you have a great weekend!
