### ISSUE TITLE
In latest master, submitting files seems to be broken

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#48]
We can't get it to recognise *any* filetypes...

File submitted to cm:301764 with an extension docx This assignment is configured to ignore this filetype, only files of type:0 are accepted

   line 918 of /plagiarism/urkund/lib.php: call to debugging()
   line 679 of /plagiarism/urkund/lib.php: call to urkund_queue_file()
   line 37 of /plagiarism/urkund/classes/observer.php: call to plagiarism_plugin_urkund->event_handler()
   line ? of unknownfile: call to plagiarism_urkund_observer::assignsubmission_file_uploaded()
   line 155 of /lib/classes/event/manager.php: call to call_user_func()
   line 75 of /lib/classes/event/manager.php: call to core\event\manager::process_buffers()
   line 721 of /lib/classes/event/base.php: call to core\event\manager::dispatch()
   line 238 of /mod/assign/submission/file/locallib.php: call to core\event\base->trigger()
   line 5851 of /mod/assign/locallib.php: call to assign_submission_file->save()
   line 5920 of /mod/assign/locallib.php: call to assign->save_submission()
   line 404 of /mod/assign/locallib.php: call to assign->process_save_submission()
   line 53 of /mod/assign/view.php: call to assign->view()

and...

File submitted to cm:301764 with an extension pdf This assignment is configured to ignore this filetype, only files of type:0 are accepted

   line 918 of /plagiarism/urkund/lib.php: call to debugging()
   line 679 of /plagiarism/urkund/lib.php: call to urkund_queue_file()
   line 37 of /plagiarism/urkund/classes/observer.php: call to plagiarism_plugin_urkund->event_handler()
   line ? of unknownfile: call to plagiarism_urkund_observer::assignsubmission_file_uploaded()
   line 155 of /lib/classes/event/manager.php: call to call_user_func()
   line 75 of /lib/classes/event/manager.php: call to core\event\manager::process_buffers()
   line 721 of /lib/classes/event/base.php: call to core\event\manager::dispatch()
   line 238 of /mod/assign/submission/file/locallib.php: call to core\event\base->trigger()
   line 5851 of /mod/assign/locallib.php: call to assign_submission_file->save()
   line 5920 of /mod/assign/locallib.php: call to assign->save_submission()
   line 404 of /mod/assign/locallib.php: call to assign->process_save_submission()
   line 53 of /mod/assign/view.php: call to assign->view()

etc.

**Comment by danmarsden** [comment]
whoops - that will be for assignments that were set-up/created before this version - If you edit the settings of the assignment and re-save the settings it should fix that up but I'll write a patch to fix it properly later today. Thanks!

**Comment by danmarsden** [comment]
I've just pushed a fix that should address this - apologies for missing this during my testing... one day I might implement some behat testing... :-)
