### ISSUE TITLE
click submit button can be removed while Submit file when student sends for marking is enabled

### ISSUE THREAD

**Issue by FuzzyHero** [danmarsden/moodle-plagiarism_urkund#49]
It is possible remove the submit but still have the file set to only send to URKUND once submit button is clicked. This means files have not been sent to URKUND for checking.

## How to reproduce:
**Submission settings**
In **Require students click submit button** select **Yes** from the drop-down.

**URKUND plagiarism plugin**
In **Enable URKUND** select **Yes** from the drop-down
In **When should the file be submitted to URKUND** select **Submit file when student sends for marking**

Now return to **Submission settings**
In **Require students click submit button** select **No** from the drop-down.

**Comment by danmarsden** [comment]
Thanks for the report! - I've pushed a fix through to address this into github.
