### ISSUE TITLE
Urkund queue blocked

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#52]
We are currently running the older version on our production server and the queue has 'stuck' (again). I wanted to make sure the new updates will prevent this. The debugging page is currently showing this under "Held events"...

stdClass Object
(
    [id] => 1649727
    [status] => 83
    [timemodified] => 1448993261
    [eventdata] => stdClass Object
        (
            [modulename] => assign
            [cmid] => 378438
            [itemid] => 207236
            [courseid] => 6861
            [userid] => 53757
            [file] => Array
                (
                    [30d99f09083aa36841c9f3f52400bfffc6de3607] => stored_file Object
                        (
                            [fs:stored_file:private] => file_storage Object
                                (
                                    [filedir:file_storage:private] => /moodledata/moodle2/filedir
                                    [trashdir:file_storage:private] => /moodledata/moodle2/trashdir
                                    [tempdir:file_storage:private] => /moodledata/moodle2/temp/filestorage
                                    [dirpermissions:file_storage:private] => 511
                                    [filepermissions:file_storage:private] => 438
                                )

                            [file_record:stored_file:private] => stdClass Object
                                (
                                    [id] => 5709902
                                    [contenthash] => 0aaef4e476010cb899416436ba8effeb8126aca3
                                    [pathnamehash] => 30d99f09083aa36841c9f3f52400bfffc6de3607
                                    [contextid] => 648536
                                    [component] => assignsubmission_file
                                    [filearea] => submission_files
                                    [itemid] => 207236
                                    [filepath] => /
                                    [filename] => ACCFIN5017_Group11.pdf
                                    [userid] => 53757
                                    [filesize] => 1988123
                                    [mimetype] => application/pdf
                                    [status] => 0
                                    [source] => ACCFIN5017_Group11.pdf
                                    [author] => Kristy Mcilwain
                                    [license] => allrightsreserved
                                    [timecreated] => 1448978339
                                    [timemodified] => 1448978341
                                    [sortorder] => 0
                                    [referencefileid] => 
                                    [repositoryid] => 
                                    [reference] => 
                                    [referencelastsync] => 
                                )

                            [filedir:stored_file:private] => /moodledata/moodle2/filedir
                            [repository:stored_file:private] => 
                        )

                )

            [pathnamehashes] => Array
                (
                    [0] => 30d99f09083aa36841c9f3f52400bfffc6de3607
                )

        )

    [stackdump] => line 726 of lib/classes/event/base.php: call to events_trigger_legacy()
line 238 of mod/assign/submission/file/locallib.php: call to core\event\base->trigger()
line 5851 of mod/assign/locallib.php: call to assign_submission_file->save()
line 5920 of mod/assign/locallib.php: call to assign->save_submission()
line 404 of mod/assign/locallib.php: call to assign->process_save_submission()
line 53 of mod/assign/view.php: call to assign->view()

    [userid] => 53757
    [eventname] => assessable_file_uploaded
    [component] => plagiarism_urkund
    [handlerfile] => /plagiarism/urkund/lib.php
    [handlerfunction] => s:26:"urkund_event_file_uploaded";
)

There is nothing in mdl_plagiarism_urkund_files for userid=53757

Digging that out of the queue...

> select * from mdl_events_queue_handlers where id=1649727\G
*************************** 1. row ***************************
           id: 1649727
queuedeventid: 1649732
    handlerid: 43
       status: 90
 errormessage: Handler function of component plagiarism_urkund: s:26:"urkund_event_file_uploaded"; threw exception :Error reading from database
* line 1080 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
* line 1307 of /lib/dml/moodle_database.php: call to mysqli_native_moodle_database->get_records_sql()
* line 626 of /plagiarism/urkund/lib.php: call to moodle_database->get_records_select()
* line 743 of /plagiarism/urkund/lib.php: call to plagiarism_plugin_urkund->event_handler()
* line ? of unknownfile: call to urkund_event_file_uploaded()
* line 299 of /lib/eventslib.php: call to call_user_func()
* line 343 of /lib/eventslib.php: call to events_dispatch()
* line 450 of /lib/eventslib.php: call to events_process_queued_handler()
* line 45 of /lib/classes/task/events_cron_task.php: call to events_cron()
* line 74 of /lib/cronlib.php: call to core\task\events_cron_task->execute()
* line 61 of /admin/cli/cron.php: call to cron_run()
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')  ORDER BY id' at line 1
SELECT * FROM mdl_plagiarism_urkund_files WHERE cm = ? AND userid IN ()  ORDER BY id
[array (
  0 => '378438',
)]
 timemodified: 1448994583
1 row in set (0.00 sec)

So, the lack of that entry appears to be the sticking point. 

The big question is does the new version fix whatever this is?

**Comment by danmarsden** [comment]
Yes - I'm pretty sure that is fix #44 - feel free to cherry pick that and it should clear the queue. The new events API shouldn't suffer from the queue being held up like this either.

**Comment by thepurpleblob** [comment]
BTW... I don't know if this is related but now when I click 'Get score' on successful submissions I see...

An error occurred trying to send this file to URKUND
stdClass Object
(
    [id] => 36205
    [cm] => 392554
    [userid] => 45566
    [identifier] => 5fdafb1a1135f0fc10efeb68babc5153938d45be
    [filename] => 2162220 Final Essay submission.doc
    [reporturl] => https://secure.urkund.com/view/16552207-394935-964438
    [optout] => https://secure.urkund.com/account/document/exemptionstatus/16503931-693553-124041
    [statuscode] => Analyzed
    [similarityscore] => 20
    [attempt] => 1
    [errorresponse] => 
    [timesubmitted] => 1449047931
)

I stuck debugging on and didn't get anything extra.

**Comment by danmarsden** [comment]
yeah - that's actually a "successful" returned score with the statuscode = analyzed and the similarityscore returned there. the debug page is reporting incorrectly that an error occured. I've pushed a fix for that. Thanks.

**Comment by danmarsden** [comment]
I think this can be closed but let me know if I've missed anything else here.
