### ISSUE TITLE
Group submit doesn't work in some circumstances

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#53]
This is from one of our QA testers. I hope it makes sense...

Group submit tests x3 = first broken and other 2 work

Create a course
Add 4 students to the course
Create 2 groups with 2 students
Create an assignment
Enable submit button for submission
Enable group submission
Enable URKUND where report is generated once student submits work for marking.
Login as student and make submission
'''Expect to see URKUND cog icon but nothing visible beside file.'''

Create a course
Add 4 students to the course
Create 2 groups with 2 students
Create an assignment
Enable group submission
Enable URKUND where report is generated straight away.
Enable blind marking
Login as student and make submission
'''Expect to see URKUND cog icon – cog icon now visible and working.'''

Create a course
Add 4 students to the course
Create 2 groups with 2 students
Create an assignment
Enable group submission
Enable URKUND where report is generated straight away.
Login as student and make submission
'''Expect to see URKUND cog icon – cog icon visible and working.'''

Looks like having student submit file for marking before getting report breaks it.

**Comment by thepurpleblob** [comment]
More tests...

Individual submit tests x3 = first broken and other 2 work this time too.
Create a course
Add 4 students to the course
Create an assignment
Enable submit button for submission
Enable URKUND where report is generated once student submits work for marking.
Login as student and make submission
Expect to see URKUND cog icon but nothing visible beside file.



Create a course
Add 4 students to the course
Create an assignment
Enable URKUND where report is generated straight away.
Enable blind marking
Login as student and make submission
Expect to see URKUND cog icon – cog icon now visible and working.


Create a course
Add 4 students to the course
Create an assignment
Enable URKUND where report is generated straight away.
Login as student and make submission
Expect to see URKUND cog icon – cog icon visible and working.


Again looks like having student submit file for marking before getting report breaks it.

**Comment by thepurpleblob** [comment]
Right... they're all sitting 'pending' in the debug page. Cron is definitely running and (running it manually) it skips through the Plagiarism bit with no messages at all. They stay pending. When I try to resubmit one of them I get errors...

Notice: Undefined variable: plagiarismsettings in /var/www/moodle29/plagiarism/urkund/urkund_debug.php on line 118

Fatal error: Call to a member function get_filename() on a non-object in /var/www/moodle29/plagiarism/urkund/lib.php on line 988

**Comment by danmarsden** [comment]
thanks - that's really great, I was hoping someone would be able to test the group submission stuff - I'll get that sorted and we can release this into the plugins db.

**Comment by danmarsden** [comment]
although - now that I look at those scenarios - has the submit for marking button been hit by the student? - the assignment is configured to only send the file to urkund when submit for marking is hit - the "cog" won't show on draft assignments as they aren't sent for processing. The Cog should only appear when the file is sent for marking.

**Comment by danmarsden** [comment]
(the fatal error noticed on the debug page should be fixed in github now though.)

**Comment by thepurpleblob** [comment]
I checked with the tester (who is very familiar with Moodle) and he assures me that the 'Submit for marking' button was pressed. This is a typical db entry from one of those files...

select * from mdl_plagiarism_urkund_files where id=1906\G
*************************** 1. row ***************************
             id: 1906
             cm: 301790
         userid: 48
     identifier: 9ce0958c3afbac8d7985bfda264122cb95ae3e44
       filename: sydb.doc
      reporturl: NULL
         optout: NULL
     statuscode: pending
similarityscore: 0
        attempt: 0
  errorresponse: NULL
  timesubmitted: 1449057834

I've not seen 'pending' before as a statuscode.

**Comment by thepurpleblob** [comment]
Not sure what I did differently, but finally tracked down an error..

Scheduled task failed: Send queued files,Invalid course module ID
Debug info:
SELECT id,course FROM {course_modules} WHERE id = ?
[array (
  0 => '301778',
)]
Backtrace:
* line 1429 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
* line 7145 of /lib/accesslib.php: call to moodle_database->get_record()
* line 1377 of /plagiarism/urkund/lib.php: call to context_module::instance()
* line 1450 of /plagiarism/urkund/lib.php: call to plagiarism_urkund_get_file_object()
* line 45 of /plagiarism/urkund/classes/task/send_files.php: call to plagiarism_urkund_send_files()
* line 74 of /lib/cronlib.php: call to plagiarism_urkund\task\send_files->execute()
* line 61 of /admin/cli/cron.php: call to cron_run()

**Comment by thepurpleblob** [comment]
So.... I deleted the entry in mdl_plagiarism_urkund_files for the missing course module. I re-ran the cron and everything went this time. I can only assume that the tester deleted the assignment between the submission and it getting sent. 

So (again)... can I suggest that this be made a bit more robust by adding a check that the cm really exists and not fail completely if it doesn't :)

**Comment by danmarsden** [comment]
found an issue with the way draft assignments were being handled - seems to be working for me now.
