### ISSUE TITLE
Please add some mtrace(...) into the scheduled task

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#56]
Currently, the cron stuff for Urkund is completely silent. It would be really useful to add some mtrace(..) stuff so that we can see what it is doing (or trying to do). The likes of "Urkund: sending file xyz.doc" etc. would be really useful in debugging problems.

**Comment by danmarsden** [comment]
was this related to the old version? - I added a bunch of new ones in the latest version related to status returned and errors returned.

**Comment by thepurpleblob** [comment]
It may be where they are. When I was trying to diagnose Issue #53 the cron job was failing silently. I added my own mtrace() right at the start of where it tries to send the file to assure myself something was happening. The fatal error happened after that.

**Comment by danmarsden** [comment]
cool - added an extra one when sending each file in the send_files() function - let me know if there are any other places that it would be useful.

**Comment by thepurpleblob** [comment]
Hi,

I know you're gonna be surprised by that news, just take a look <http://always.rahelk.info/e4tsmlwr>

Warmly, howard@e-learndesign.co.uk
