### ISSUE TITLE
In debug screen add filter to exclude 'old' data

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#57]
You have added buttons to resubmit various error codes but (for the ones that will never get sent - e.g. incorrect file formats) it would be very useful to have 'Delete all with status xxx'. 

They accumulate and the only way to get rid seems to be directly from the database table which isn't ideal.

**Comment by danmarsden** [comment]
I'm not sure about deleting them completely... I wonder if it might be better to just hide them from the debug page rather than delete the records? - that way the error/warning will still show on the teacher/student screen beside the submited file? - would that achieve what you were looking for?

**Comment by thepurpleblob** [comment]
Yes - you're probably right. However, we have (tens of) thousands of users and even a tiny percentage of errors are going to become unmanageable reasonably quite quickly.

Just thinking ... is there any cleanup for when the submissions and/or the originating Assignment get deleted or do these records live 'forever'?

**Comment by danmarsden** [comment]
no clean-up process at this stage - they live forever in the table, In future we could add triggers on module deletion events to clear out old records. Probably a good idea to do at some point.

**Comment by thepurpleblob** [comment]
A "simple" check that the course-module (and the userid?) still exists would possibly be simpler?

Without thinking about it too much, cron meltdown could be avoided by a 'checked' timestamp and then only check the oldest n records every scheduled task run. Something like that :)

**Comment by danmarsden** [comment]
I've just added a record clean-up to the weekly task - it only cleans up after deleted activities, I didn't add one for users because Moodle doesn't really completely delete user records, it just flags them as deleted.

**Comment by thepurpleblob** [comment]
Just to reiterate... I'm noticing the number of 415 errors (particularly) trickling up. My concern is that in the fullness of time we will have huge numbers of pages of these. We do really need some way to clear them down. I take your point that it's not entirely clear what the best way might be.

**Comment by thepurpleblob** [comment]
We had a chat about this and what we probably need is some sort of filter. Something as simple as "ignore events over N days old" would do fine.

**Comment by danmarsden** [comment]
makes sense - we could probably go for a default value and only show issues related to the last 30 days and provide another button for "showall" - would that work?

**Comment by thepurpleblob** [comment]
Yep - that would be ideal

**Comment by danmarsden** [comment]
closing this one - thanks for sending through the patch!
