### ISSUE TITLE
After upgrade, don't seem to be able to resubmit 613 errors

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#60]
Get this message...

"URKUND fileid:39869 no files found with this record URKUND fileid:39874 sending to URKUND"

Also, trying a few individual ones... while a few 'work' the result for the others is a mostly a variation on the above or (with debugging on) the following...

Fatal error: Call to a member function get_filename() on a non-object in /var/www/html/moodle/plagiarism/urkund/lib.php on line 943

I also tried to resubmit 'Pending' submissions and this also fails...
Fatal error: Call to undefined method stdClass::get_content() in /var/www/html/moodle/plagiarism/urkund/lib.php on line 975

I'm getting a bit lost, but I'm assuming that these are pre-upgrade submissions that have somehow got orphaned as part of the upgrade process. Bit worried to be honest.

**Comment by danmarsden** [comment]
those look like errors due to a bug in the reset process - I've just pushed a commit that might fix that up. let me know if it fixes it - thanks heaps for the reports/testing - sorry that you've ended up being the guinea pigs! :-)

**Comment by thepurpleblob** [comment]
I'm not going to be able to update the plugin again until next week. Just a thought though. The message you get...

URKUND fileid:44440 no files found with this record URKUND fileid:44527 no files found with this record URKUND fileid:44528 sending to URKUND

isn't very helpful. It doesn't reference any information that you can actually search for on the Debugging table/list to find the submission and (probably) delete it.

**Comment by danmarsden** [comment]
yeah - the newer version cleans out some of those records anyway so you don't need to delete it yourself. I'll think about adding more info to the messages in cron.

**Comment by danmarsden** [comment]
I think this particular one is sorted - closing it but we can re-open again if needed.

**Comment by thepurpleblob** [comment]
Hi,

I wanted to tell you how much our friendship means to me and to show you some things that ainspire me, take a look here, please <http://amazing.librariansguidetolove.com/e4xpie>

Yours truly, howard@e-learndesign.co.uk
