### ISSUE TITLE
Sending pending files appears to be broken...

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#64]
In cron output....

Execute scheduled task: Send queued files
... started 10:48:57. Current memory use 52MB.
URKUND fileid:42397 sending for processing
URKUND fileid:42397 file not found
URKUND fileid:42405 sending for processing
URKUND fileid:42405 file not found
URKUND fileid:42406 sending for processing
URKUND fileid:42406 file not found
URKUND fileid:42410 sending for processing
URKUND fileid:42410 file not found
URKUND fileid:42560 sending for processing
URKUND fileid:42560 file not found
URKUND fileid:42594 sending for processing
URKUND fileid:42594 file not found
URKUND fileid:42603 sending for processing
URKUND fileid:42603 file not found
URKUND fileid:42645 sending for processing
URKUND fileid:42645 file not found
URKUND fileid:42703 sending for processing
URKUND fileid:42703 file not found
URKUND fileid:42707 sending for processing
URKUND fileid:42707 file not found
URKUND fileid:42739 sending for processing
URKUND fileid:42739 file not found
URKUND fileid:42750 sending for processing
URKUND fileid:42750 file not found
URKUND fileid:42872 sending for processing
URKUND fileid:42872 file not found
URKUND fileid:43036 sending for processing
URKUND fileid:43036 file not found
URKUND fileid:43051 sending for processing
URKUND fileid:43051 file not found
URKUND fileid:43529 sending for processing
URKUND fileid:43529 file not found
URKUND fileid:43546 sending for processing
URKUND fileid:43546 file not found
URKUND fileid:43669 sending for processing
URKUND fileid:43669 file not found
URKUND fileid:43835 sending for processing
URKUND fileid:43835 file not found
URKUND fileid:43986 sending for processing
URKUND fileid:43986 file not found
URKUND fileid:44078 sending for processing
URKUND fileid:44078 file not found
URKUND fileid:44106 sending for processing
URKUND fileid:44106 file not found
URKUND fileid:44536 sending for processing
URKUND fileid:44536 file not found
URKUND fileid:44569 sending for processing
URKUND fileid:44569 file not found
URKUND fileid:44590 sending for processing
URKUND fileid:44590 file not found
URKUND fileid:44616 sending for processing
URKUND fileid:44616 file not found
URKUND fileid:44692 sending for processing
URKUND fileid:44692 file not found
URKUND fileid:45000 sending for processing
URKUND fileid:45000 file not found
URKUND fileid:45001 sending for processing
URKUND fileid:45001 file not found
URKUND fileid:45012 sending for processing
URKUND fileid:45012 file not found
URKUND fileid:45042 sending for processing
URKUND fileid:45042 file not found
URKUND fileid:45117 sending for processing
URKUND fileid:45117 file not found
URKUND fileid:45119 sending for processing
URKUND fileid:45119 file not found
URKUND fileid:45140 sending for processing
URKUND fileid:45140 file not found
URKUND fileid:45221 sending for processing
URKUND fileid:45221 file not found
URKUND fileid:45340 sending for processing
URKUND fileid:45340 file not found
URKUND fileid:45414 sending for processing
URKUND fileid:45414 file not found
URKUND fileid:45415 sending for processing
URKUND fileid:45415 file not found
URKUND fileid:45658 sending for processing
URKUND fileid:45658 file not found
URKUND fileid:45750 sending for processing
URKUND fileid:45750 file not found
URKUND fileid:45811 sending for processing
URKUND fileid:45811 file not found
URKUND fileid:45842 sending for processing
URKUND fileid:45842 file not found
URKUND fileid:45978 sending for processing
URKUND fileid:45978 file not found
URKUND fileid:45994 sending for processing
URKUND fileid:45994 file not found
URKUND fileid:45998 sending for processing
URKUND fileid:45998 file not found
URKUND fileid:46033 sending for processing
URKUND fileid:46033 file not found
URKUND fileid:46065 sending for processing
URKUND fileid:46065 file not found
URKUND fileid:46241 sending for processing
URKUND fileid:46241 file not found
URKUND fileid:46242 sending for processing
URKUND fileid:46242 file not found
URKUND fileid:46243 sending for processing
URKUND fileid:46243 file not found
URKUND fileid:46244 sending for processing
URKUND fileid:46244 file not found
URKUND fileid:46260 sending for processing
URKUND fileid:46260 sending to URKUND
URKUND fileid:46260 returned status: 202

Just taking the last broken one as an example however...

select * from mdl_plagiarism_urkund_files where id=46244\G
*************************** 1. row ***************************
             id: 46244
             cm: 390161
         userid: 52365
     identifier: 5ec76a53c50d6a172fb1d55ef5b2fe1e19a07c4b
       filename: 2225216.docx
      reporturl: NULL
         optout: NULL
     statuscode: pending
similarityscore: 0
        attempt: 0
  errorresponse: NULL
  timesubmitted: 1450714034
1 row in set (0.10 sec)

mysql> select * from  mdl_files where filename='2225216.docx'\G
*************************** 1. row ***************************
             id: 5930511
    contenthash: 5ec76a53c50d6a172fb1d55ef5b2fe1e19a07c4b
   pathnamehash: 9daaff8c8e89c4d02d5411100027e66252af30d1
      contextid: 351944
      component: user
       filearea: draft
         itemid: 788603797
       filepath: /
       filename: 2225216.docx
         userid: 52365
       filesize: 32473
       mimetype: application/vnd.openxmlformats-officedocument.wordprocessingml.document
         status: 0
         source: O:8:"stdClass":1:{s:6:"source";s:12:"2225216.docx";}
         author: Diane Carr
        license: allrightsreserved
    timecreated: 1450714033
   timemodified: 1450714033
      sortorder: 0
referencefileid: NULL
*************************** 2. row ***************************
             id: 5930512
    contenthash: 5ec76a53c50d6a172fb1d55ef5b2fe1e19a07c4b
   pathnamehash: f2cb56167c3acf3a3eb5067d1e7261144d9a7f69
      contextid: 679835
      component: assignsubmission_file
       filearea: submission_files
         itemid: 289877
       filepath: /
       filename: 2225216.docx
         userid: 52365
       filesize: 32473
       mimetype: application/vnd.openxmlformats-officedocument.wordprocessingml.document
         status: 0
         source: 2225216.docx
         author: Diane Carr
        license: allrightsreserved
    timecreated: 1450714033
   timemodified: 1450714034
      sortorder: 0
referencefileid: NULL
2 rows in set (5.59 sec)

This one was submitted about 4pm yesterday so it's a current issue.

Resubmitting 'pending' through the error page has the same result - mass of 'file not found' errors.

The code in plagiarism_urkund_get_file_object is not exactly trivial so I'm struggling to see what might have gone wrong but it doesn't seem to be finding any pending files. 

Just to note that I attempted to reproduce this on my test system (identical code base) and it all works as expected. Submission is 'pending' and then 'Resubmit all pending' from the debugging page transforms it into a 202.

**Comment by danmarsden** [comment]
which version are you using on the prod site? - is it different from the version on testing? - there were a few issues that I fixed that I think I may have fixed after you upgraded your prod.

**Comment by thepurpleblob** [comment]
Bang up to date master version (as of a couple of days ago... don't think you have changed anything since)

**Comment by danmarsden** [comment]
cool - taking a look at the debug info you have provided and will see if I can find any possible cause.

**Comment by danmarsden** [comment]
I'm seeing some issues with the following workflow
students submits file 1
student submits file 2 which overwrites file 1

both generate a record in the table, but file 1 returns a file not found error and always remains in a pending state. This record should get deleted because it has been replaced with a new submission.

I'm not sure if that is the same situation you are experiencing though - would be good to check to see if the users have multiple records in the plagiarism_urkund_files table for the same assignment and if a "newer" submission has returned a result.

**Comment by thepurpleblob** [comment]
Is my example (the database query) not a demonstration of just that? 

I think the nature of the thing is that (where allowed) they will upload multiple versions until they get a plagiarism score they are happy with. Our institution's policy dictates that they must be allowed at least two shots.

**Comment by danmarsden** [comment]
possibly - but in your example above you are only showing one plagiarism_urkund_files record - can you check to see if more than one record in that table exists for the user/cm in your example? 52365/390161

**Comment by danmarsden** [comment]
if that is the case - this particular issue will mainly be filling up the logs/error page but shouldn't be affecting students because their most valid submission will still be processed.

**Comment by thepurpleblob** [comment]
Nope...

select * from mdl_plagiarism_urkund_files where cm=390161 and userid=52365;

only returns the one result.

**Comment by thepurpleblob** [comment]
The very first one on the list, however...

mysql> select * from mdl_plagiarism_urkund_files where id=42397\G
*************************** 1. row ***************************
             id: 42397
             cm: 371181
         userid: 24182
     identifier: 1fdd034a52fcbac05d9bbc5d19b9b49388eaa42b
       filename: 2039721.pdf
      reporturl: NULL
         optout: NULL
     statuscode: pending
similarityscore: 0
        attempt: 0
  errorresponse: NULL
  timesubmitted: 1449830472

mysql> select * from mdl_plagiarism_urkund_files where cm=371181 and userid=24182\G
*************************** 1. row ***************************
             id: 42397
             cm: 371181
         userid: 24182
     identifier: 1fdd034a52fcbac05d9bbc5d19b9b49388eaa42b
       filename: 2039721.pdf
      reporturl: NULL
         optout: NULL
     statuscode: pending
similarityscore: 0
        attempt: 0
  errorresponse: NULL
  timesubmitted: 1449830472
*************************** 2. row ***************************
             id: 42400
             cm: 371181
         userid: 24182
     identifier: 6026a7ac266d1659060070f258e3ddc036962f30
       filename: 2039721.pdf
      reporturl: https://secure.urkund.com/view/16730846-854575-158064
         optout: https://secure.urkund.com/account/document/exemptionstatus/16682774-388552-572847
     statuscode: Analyzed
similarityscore: 1
        attempt: 1
  errorresponse: NULL
  timesubmitted: 1449830672

**Comment by thepurpleblob** [comment]
The one after that....

mysql> select * from mdl_plagiarism_urkund_files where id=42405\G
*************************** 1. row ***************************
             id: 42405
             cm: 406141
         userid: 66202
     identifier: 27cdb8d7fe8a4cc66cf215703044a7ebc1e4b3ce
       filename: 2221593_ECON4012_2.docx
      reporturl: NULL
         optout: NULL
     statuscode: pending
similarityscore: 0
        attempt: 0
  errorresponse: NULL
  timesubmitted: 1449830919
1 row in set (0.01 sec)

mysql> select * from mdl_plagiarism_urkund_files where cm=406141 and userid=66202\G
*************************** 1. row ***************************
             id: 36483
             cm: 406141
         userid: 66202
     identifier: fad8cf158827ebdb5bd7ec6480b0c9d17e273b02
       filename: Econessay2.docx
      reporturl: https://secure.urkund.com/view/16562644-624126-948648
         optout: https://secure.urkund.com/account/document/exemptionstatus/16513873-333682-480770
     statuscode: Analyzed
similarityscore: 26
        attempt: 1
  errorresponse: NULL
  timesubmitted: 1449073176
*************************** 2. row ***************************
             id: 42071
             cm: 406141
         userid: 66202
     identifier: c9a546a2f608c85ca7562c5faeebc42dd62c5fd6
       filename: Econessay2 (1).docx
      reporturl: https://secure.urkund.com/view/16720417-655781-603469
         optout: https://secure.urkund.com/account/document/exemptionstatus/16672545-288759-552294
     statuscode: Analyzed
similarityscore: 14
        attempt: 1
  errorresponse: NULL
  timesubmitted: 1449781466
*************************** 3. row ***************************
             id: 42355
             cm: 406141
         userid: 66202
     identifier: 82a91b7f7b88800ed9df96827eda996f893d6080
       filename: LOOKATTHISESSAY.docx
      reporturl: https://secure.urkund.com/view/16728096-413484-704497
         optout: https://secure.urkund.com/account/document/exemptionstatus/16679348-486744-980992
     statuscode: Analyzed
similarityscore: 14
        attempt: 1
  errorresponse: NULL
  timesubmitted: 1449827284
*************************** 4. row ***************************
             id: 42405
             cm: 406141
         userid: 66202
     identifier: 27cdb8d7fe8a4cc66cf215703044a7ebc1e4b3ce
       filename: 2221593_ECON4012_2.docx
      reporturl: NULL
         optout: NULL
     statuscode: pending
similarityscore: 0
        attempt: 0
  errorresponse: NULL
  timesubmitted: 1449830919
*************************** 5. row ***************************
             id: 42412
             cm: 406141
         userid: 66202
     identifier: b5a8250affe5d1a0e3418de3f01ebffc44f07499
       filename: 2221593_ECON4012_2.docx
      reporturl: https://secure.urkund.com/view/16731068-922518-442802
         optout: https://secure.urkund.com/account/document/exemptionstatus/16682783-414106-849493
     statuscode: Analyzed
similarityscore: 12
        attempt: 9
  errorresponse: NULL
  timesubmitted: 1449831099
5 rows in set (0.00 sec)

So, yeh, this may be the answer for some or, hopefully, most of them :)

**Comment by thepurpleblob** [comment]
There could be nothing wrong. But... we have low level complaints of delays. Plus 202 status files building up in debug and the above. I may just be getting very twitchy. But you know when you have a feeling something isn't quite right...

**Comment by danmarsden** [comment]
cool - so we've narrowed down one issue which is good - the fix will be to delete those extra records but I'd like to trace the other issue there as well before we delete records that don't have an associated file record. I wonder if cm=390161 and userid=52365 is another occurrence of the issue you are seeing in #63 

Can you take a look at the list of submitted assignments in the cm=390161 (teacher view) and check to see if a cog or any other icon appears beside the file submitted by userid 52365  
If no icon appears it sounds like the contenthash in the db doesn't match the contenthash of the actual submitted file and somehow a 2nd record hasn't been created correctly.

**Comment by thepurpleblob** [comment]
There is no submission and that user is a Teacher in the course. Is this where the teacher has edited a student's submission? Possibly from some time ago?

**Comment by danmarsden** [comment]
ok - so the "good" thing is that the record isn't valid as there is no submission - so the code I've written to clean-up the other duplicate instances will clean this particular one up as well. If it's the teacher account it might in fact be Issue #40

**Comment by danmarsden** [comment]
I've tidied up the plagiarism_urkund_send_files() function so that it deletes old records that don't contain a valid file - rather than leaving them in a "pending" state. Hopefully that should tidy up your debug page :-)

**Comment by thepurpleblob** [comment]
Great.... we'll give that a bash :)
