### ISSUE TITLE
teacher 'submit file for grading' option doesn't seem to work

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#67]
- set up an assignment such that the students must press the submit button for marking and that Urkund is set so that their file is only processed when the submit button is pressed. 
- submit a file. 
- as a teacher, revert the file to draft, submit a new file and then 'submit file for grading' all through the teacher/grading interface.

The file is not submitted to Urkund :(

**Comment by danmarsden** [comment]
bummer - I was hoping the last patch I pushed through would sort that. I presume you're using the latest code? I wonder if the relateduserid is being passed correctly in the core event?

**Comment by thepurpleblob** [comment]
Latest code. 

But hold on... You definitely improved it :). It's now only an issue when the assignment is set up to send when the student presses the submit button. It does work when it is set to submit as soon as a file is uploaded (it didn't before). 

I haven't checked, but I wonder if changing the submission status from the teacher menu triggers the event at all - it could actually be an assignment issue.

**Comment by danmarsden** [comment]
thanks Howard - I'll take a look either later tonight when I get back to the office or early next week.

**Comment by thepurpleblob** [comment]
My suspicion are that these are assignments that where the student is required to submit their work and they must tick the box the accept a policy statement. In this case, submitting or changing the file on their behalf doesn't work. It is 'ignored' by Urkund. 

"Logging in as" the student does seem to work. 

Worryingly (although I need to do more work on this), it seems that if the teacher does submit on behalf if the student in these circumstances it breaks the submission. The Urkund status vanishes and even the student can no longer re-submit it successfully.

**Comment by danmarsden** [comment]
btw - these missing reports - I assume they don't use an extension that is excluded from the urkund assignment settings page? - if the urkund settings for "Allow all supported file types" is set to "No" only files with the selected file-types will be sent to URKUND and have a record added in the plagiarism table.

**Comment by thepurpleblob** [comment]
We get lots of issues with students trying to send unsupported file types. The typical two are Apple Pages and missing the extension of a (legit) file name. I think the issues lies with what they do next. However, it may well be related to staff re-submitting the document for them. In which case the file becomes owned by the member of staff and it then seems to be irrevocably broken.

**Comment by danmarsden** [comment]
yeah - if we could work out an exact way to reproduce this it would help a lot - I haven't been able to reproduce it myself.

**Comment by danmarsden** [comment]
the original issue "teacher submit for grading" reported here seems to be working ok now.

I've tried various combinations of teacher uploading and submitting, student uploading, teacher submitting, teacher uploading, student submitting and all seems to work with the latest changes. But let me know if I've missed something (again) and I'll take (another) look! :-)
