### ISSUE TITLE
Re-sending files that had 415 error doesn't work

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#68]
...even if you delete them from mdl_plagiarism_urkund_files.

I think the scenario goes something like this...

- student uploads a 'pages' file or a file with no extension or similar.
- They get the warning icon and we see a 415 error recorded in the debugging page
- we advise them to resubmit
- they now get no score, no Urkund icons at all and no entry in the urkund_files table in respect of this new submission. 
- even if we delete the extant 415 from the debugging screen it makes no difference. The submission in that Assignment for that student will not go to Urkund. It doesn't matter if the student does it or we do it on behalf of the student. 

EDIT:
We have been talking about this and we are fairly sure that we have seen re-submitting broken files working fine in some places but stubbornly refusing to do so in others. We haven't (yet) done any work on trying to figure out what the difference might be or tried to reproduce this on a test server. I'm hoping you have an inspired idea as I can see us potentially having to spend quite a lot of time on this. 

EDIT EDIT:
Is it possible that there is an issue where very old assignments have Urkund enabled long after some submissions have been made. At least one of the assignments seems to have been in use (i.e. has submissions) during a term prior to the introduction of Urkund. Obviously we don't expect the older submissions to be processed but I wonder if this might have a detrimental effect on submissions since Urkund was enabled?

**Comment by thepurpleblob** [comment]
Just to demonstrate. I reverted a submission (with a missing Urkund entry) to draft, logged in as the user and resubmitted their essay. Still not a sniff from Urkund. Log excerpt

![screen shot 2016-01-07 at 14 42 49](https://cloud.githubusercontent.com/assets/664139/12173176/34cfc754-b54d-11e5-9603-17463662ac89.png)

**Comment by danmarsden** [comment]
415 = unsupported file type submitted, we probably need to improve the docs - it can either be a valid response from an API call or "autodetected" based on file extension and core list of supported files in code. I would usually expect a re-submit of a valid 415 "error" to return a 415 each time. (unless your'e doing this against Turnitin's API which didn't always report this error correctly) :-)

It would be good to check what file-type is being submitted.

we should probably improve the debugging log page - but I thought the teacher view/student view already gave a useful error (file type not supported)

**Comment by thepurpleblob** [comment]
A typical scenario is that a student submits in an unsupported type (usually Apple's Pages) or that they miss off the file extension. Anyway, it doesn't work and they end up with a 415 error. 

Somebody tells them to resubmit, so they change the file to a correct one and it just 'breaks'. Any indication of Urkund status vanishes and cannot be restored no matter what we try. 

I believe (unfortunately) that this is intermittent. We can't reproduce it on test boxes.

**Comment by danmarsden** [comment]
I suspect this might be a duplicate of #67 #71 if it's happening intermittently - has the teacher downloaded it, re-saved and uploaded the newer version?

**Comment by thepurpleblob** [comment]
It *is* possible that it has the same underlying cause although the end result is slightly different. We have students complaining that they were advised to re-submit a submission in error (a 415 error) and they find it to be completely stuffed. Now no Urkund markup on the Assignment screen and nothing we or they do seems to want to bring it back. Unfortunately, it's proving difficult to exactly tie down what led up to this but we have seen it many (order of tens) times now.

**Comment by danmarsden** [comment]
If you can provide a way for me to reproduce it let me know and I'll try to look closer. I'm going to take a look at some of the events in core today to see if there are any inconsistencies there.

**Comment by thepurpleblob** [comment]
My colleague reproduced one aspect of this in another (closed?) thread. We'll have a look (our) tomorrow and see if we can get a better idea of what's going on. I've struggled to reproduce anything away from the production servers but there's clearly something odd going on. I am well aware how useless this is :)

**Comment by danmarsden** [comment]
hehe - all good, hopefully you'll find the missing piece that allows us to reproduce this!

**Comment by thepurpleblob** [comment]
I'm pretty sure that this related to old assignments that existed before a round of upgrades. Complaints seem to have dried up so I'm just going to close this. If it comes up again we'll re-open with proper information.
