### ISSUE TITLE
CSS for ".plagiarismreport .rank9" is illegible

### ISSUE THREAD

**Issue by lexxkoto** [danmarsden/moodle-plagiarism_urkund#69]
Shows as white text on a pale yellow background.

![screen shot 2016-01-06 at 15 05 28](https://cloud.githubusercontent.com/assets/7327138/12145621/36fe6222-b487-11e5-9842-8a7780d08ca1.png)

**Comment by danmarsden** [comment]
Thanks - I'm pretty sure that URKUND supplied me with these css rankings/colours and it will depend on the theme you are using a bit. I'll have a chat with URKUND and look at changing the defaults but hopefully you can override easily using your own custom css.

**Comment by danmarsden** [comment]
I've just pushed a fix into the git branch that changes the text colour for the rank 8 and 9 to give more contrast - these styles can still be overridden using the theme settings.

**Comment by danmarsden** [comment]
(thanks for the report!)
