### ISSUE TITLE
No settings in plagiarism_urkund_config even though urkund enabled thus not working for that activity

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#70]
We are finding a number of Assignments where Urkund submissions are simply not working even though urkund is enabled. 

On investigation the urkund config table has no entry for that course module. Even disabling and re-enabling urkund in the assignment makes no difference. 

As we can't easily find them this is (potentially) a bit of a disaster
.

**Comment by danmarsden** [comment]
weird - does sound pretty difficult - I'll take a look at this tonight and get back to you. I didn't think any of the code that saved the assignment settings should have changed much to cause this. Are there any PHP errors in the logs?

**Comment by danmarsden** [comment]
I can't reproduce this... although I wonder if if is an assignment has been created "prior" to urkund being added to the site and if your site defaults are set to enable urkund by default when loading the initial "settings" page it will show the default values in the form with urkund "enabled" - and it won't actually turn URKUND "on" until the settings page is saved? - I think this is really correct behaviour (using site defaults when no values are currently set for this assignment) but I can understand how it might be confusing.

**Comment by thepurpleblob** [comment]
I couldn't reproduce it either. However, I'm reasonably sure you are correct and that these will be old Assignments (I know for a fact some are well over a year old).

We have Urkund *off* by default and always have.

The assignments that exhibit this refuse to save their Urkund settings no matter what we try so we'll go and turn up debugging and check the logs. Hopefully, something will turn up that helps

**Comment by thepurpleblob** [comment]
Turned up debugging as far as it will go - nothing displayed and nothing in the logs. I'll take a punt on doing a backup and restore of the course. If I can reproduce it off the production service I suspect I'll get to the bottom of it. 

Local politics (and possibly common sense) preclude live debugging on the production boxes :(

**Comment by thepurpleblob** [comment]
Nope... didn't survive backup and restore. It worked perfectly once restored.

**Comment by danmarsden** [comment]
it shouldn't do... I'd check the urkund reciever address though - if that's not correct on the prod site somehow it might fail to enable?

**Comment by thepurpleblob** [comment]
We have one (default) address. I have no reason to think it's anything to do with that. 

We do sometimes see the settings page refuse to save because the address is supposedly wrong but this fixes itself after a few minutes. A suspect an intermittent network/server issue between us and Urkund (but I thought I'd mention it).

**Comment by danmarsden** [comment]
I added some more debug to the save_form_elements function here:
https://github.com/danmarsden/moodle-plagiarism_urkund/blob/master/lib.php#L377

but I can't see anything else that might prevent it from saving to the db - unless you are able to provide some more info/debug output so I can reproduce this I don't have anything else I can suggest sorry!

**Comment by danmarsden** [comment]
If you can turn on db level reporting to show incoming sql queries/updates/inserts that might be interesting - to see if it actually tries to insert anything at all?

**Comment by thepurpleblob** [comment]
I'm confident that this has gone away in the latest version and must relate to old Assignments. I'm happy to close.
