### ISSUE TITLE
Possible to mess up submission settings (I think)

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#73]
- Created a new assignment. 
- Submission settings - Require students click submit button: yes
- Urkund settings - When should the file be submitted?: submit file when the student sends for marking
- Save settings.
- Edit settings
- Submission settings - Require students click submit button:no

The box for "When should the file be submitted" is now greyed out and still "submit file when student sends for marking". Submissions do not appear to be sent to Urkund in this 'state'.

**Comment by danmarsden** [comment]
It should detect this when saving the settings page here:
https://github.com/danmarsden/moodle-plagiarism_urkund/blob/master/lib.php#L374

so that when you reload the settings page it should have automatically been fixed. If that's not working let me know!

**Comment by thepurpleblob** [comment]
It's not working. Or, at least, we're getting reports of problems and when we look at the settings we see it in this state.

**Comment by danmarsden** [comment]
it was only fixed in Nov as part of issue #49 - so if they are old assignments that would make sense. Maybe I should have written an upgrade script to fix incorrect settings at the same time. I'll do that today.

**Comment by danmarsden** [comment]
here's a query which should return assignments with the wrong setting - that need the "value" set to 0

SELECT u.* from mdl_plagiarism_urkund_config u
JOIN mdl_course_modules cm ON cm.id = u.cm
JOIN mdl_assign a ON a.id = cm.instance
JOIN mdl_modules m ON m.id = cm.module
where u.name = 'urkund_draft_submit' AND m.name = 'assign' AND a.submissiondrafts = '0'
AND u.value = '1'

(Use at your own risk though - I haven't tested/verified it completely yet.) - I'll try to put a check in the upgrade code for this once I've tested it later today.

**Comment by thepurpleblob** [comment]
Found 3, and as you suggested, simply re-saving the settings page sorted it nicely :-D
