### ISSUE TITLE
What does status 'Error' mean?

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#76]
We currently have 9 submissions all 'stuck' in state 'Error'. We can resubmit them and they go to 202. but on the next cron run they go back to Error. There doesn't seem to be anything obviously wrong. 

This is possibly more a question for Urkund... not sure.

**Comment by danmarsden** [comment]
The "error" state is one returned from URKUND on requesting the score - the fact they have a 202 means the file is accepted but the "error" response suggests (to me) that they cannot process the file - looking at the code, 

You need to ask URKUND for feedback on the reason these files have failed, but I see we aren't storing the full response from those states in the "errorresponse" field in the urkund_files table - I'll add a patch to include that extra info to help debugging in future.

**Comment by danmarsden** [comment]
I've added some extra debug output to the code - closing this for now but let me know if we need to re-open once you've heard from URKUND. Thanks!

**Comment by thepurpleblob** [comment]
Yep - they are cleverly broken documents (student ingenuity). It's just not the most helpful error message (as far as the student is concerned, it's the same deal as 415 errors). However, there are so few that it's not a massive deal.

**Comment by danmarsden** [comment]
cool - one of the good things about the urkund api from a dev perspective is it's simplicity - the number of different error states presented by "another" plagiarism API is quite extensive and challenging to code :-)

It would be interesting to see if the errorresponse column shows more useful error information now that I've added it next time you see these generic error messages.
