### ISSUE TITLE
"Get all scores" says it's resetting 202s but doesn't really

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#78]
Asking for all scores clearly asks Urkund for outstanding scores. However, it doesn't reset the count. 

I think it should. This is particularly important when there has been some delay (e.g. a server outage) and we'd like to go back to checking more frequently.

**Comment by danmarsden** [comment]
cool - I'll take a look at this next time I'm working on the code.
