### ISSUE TITLE
Some reports 'Rejected' even though report generated

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#80]
We have seen reports that are status 'Rejected' in the plugin. We reset them and they go to status 202 and then 'Rejected' again (quickly). However, on chasing up with Urkund they indicate that a score has been generated for this report. 

My guess would be that this is a problem on the Urkund side, but I thought I'd flag it up in case you can think of any reason why this might be happening from the plugin pov. 

It's quite rare.

**Comment by danmarsden** [comment]
yeah - if you have the latest code with this patch - https://github.com/danmarsden/moodle-plagiarism_urkund/commit/f85f55de700606c12508f944514d975db82b2a3a

it should store the full response in the errorresponse field in the table - not sure if it will have any more helpful information but let me know if you discover anything else!

**Comment by thepurpleblob** [comment]
We do.... here is an example... 

<?xml version="1.0" encoding="UTF-8"?>
<ArrayOfSubmissionData xmlns="http://schemas.datacontract.org/2004/07/Prioinfo.Urkund.WebServices.Core.Submissions" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
   <SubmissionData>
      <Id>6758078</Id>
      <ExternalId>b5f2b23c_422285_52512_c792c4bf06ac2934103912f1b6589881733af1d9</ExternalId>
      <Filename>1005454 Methods of Social Research Essay.docx</Filename>
      <MimeType>application/vnd.openxmlformats-officedocument.wordprocessingml.document</MimeType>
      <Timestamp>2016-01-22T00:22:00</Timestamp>
      <Status>
         <Message>The document was not received or accepted by URKUND.</Message>
         <State>Rejected</State>
      </Status>
      <Document i:nil="true" />
      <Report i:nil="true" />
      <Subject i:nil="true" />
      <Message i:nil="true" />
      <Anonymous i:nil="true" />
   </SubmissionData>
   <SubmissionData>
      <Id>6856422</Id>
      <ExternalId>b5f2b23c_422285_52512_c792c4bf06ac2934103912f1b6589881733af1d9</ExternalId>
      <Filename>1005454 Methods of Social Research Essay.docx</Filename>
      <MimeType>application/vnd.openxmlformats-officedocument.wordprocessingml.document</MimeType>
      <Timestamp>2016-01-28T15:55:26</Timestamp>
      <Status>
         <Message>The document has been analyzed.</Message>
         <State>Analyzed</State>
      </Status>
      <Document>
         <Date>2016-01-28T15:55:00</Date>
         <DownloadUrl>...deleted...</DownloadUrl>
         <OptOutInfo>
            <Message>As the author of the document you have submitted, it is within your right to hide the text content from being viewed by other educational organisations. Note that by hiding the text content, you will not delete the document. The document will remain stored and checked against internal and external sources and forwarded to your tutor along with a plagiarism report. The text content might also be visible within your educational organisation, depending on their preferred settings. However, the text content of the document will not be visible for any user outside your educational organisation.

Bear in mind that by hiding your document, it will not be protected against plagiarism. This means that an unauthorised person will be able to make use of your work in the future. If you want to protect your copyright, you should leave it unhidden.

To hide the text content of your document, click the below link:</Message>
            <Url>...deleted...</Url>
         </OptOutInfo>
         <Id>17467645</Id>
      </Document>
      <Report>
         <MatchCount>17</MatchCount>
         <ReportUrl>...deleted...</ReportUrl>
         <Significance>3.68999982</Significance>
         <SourceCount>70</SourceCount>
         <Warnings />
         <Id>17496376</Id>
      </Report>
      <Subject i:nil="true" />
      <Message i:nil="true" />
      <Anonymous i:nil="true" />
   </SubmissionData>
   <SubmissionData>
      <Id>6894007</Id>
      <ExternalId>b5f2b23c_422285_52512_c792c4bf06ac2934103912f1b6589881733af1d9</ExternalId>
      <Filename>1005454 Methods of Social Research Essay.docx</Filename>
      <MimeType>application/vnd.openxmlformats-officedocument.wordprocessingml.document</MimeType>
      <Timestamp>2016-02-01T10:04:50</Timestamp>
      <Status>
         <Message>The document has been received by URKUND and is awaiting the analysis to be finished.</Message>
         <State>Accepted</State>
      </Status>
      <Document>
         <Date>2016-02-01T10:04:00</Date>
         <DownloadUrl>...deleted...</DownloadUrl>
         <OptOutInfo>
            <Message>As the author of the document you have submitted, it is within your right to hide the text content from being viewed by other educational organisations. Note that by hiding the text content, you will not delete the document. The document will remain stored and checked against internal and external sources and forwarded to your tutor along with a plagiarism report. The text content might also be visible within your educational organisation, depending on their preferred settings. However, the text content of the document will not be visible for any user outside your educational organisation.

Bear in mind that by hiding your document, it will not be protected against plagiarism. This means that an unauthorised person will be able to make use of your work in the future. If you want to protect your copyright, you should leave it unhidden.

To hide the text content of your document, click the below link:</Message>
            <Url>...deleted...</Url>
         </OptOutInfo>
         <Id>17517239</Id>
      </Document>
      <Report i:nil="true" />
      <Subject i:nil="true" />
      <Message i:nil="true" />
      <Anonymous i:nil="true" />
   </SubmissionData>
</ArrayOfSubmissionData>

**Comment by danmarsden** [comment]
that looks interesting - the code assumes that the first <submissiondata> has the correct information - have you passed that onto URKUND? - I'm not sure why it's returning conflicting information about the same file in multiple <submissiondata> items.

**Comment by thepurpleblob** [comment]
Yes - we've sent this to Urkund as well. Just covering all the bases :)

**Comment by danmarsden** [comment]
did you hear anything back from URKUND about this one? - is it a problem on their end or should I be modifying the code to handle this situation?

**Comment by danmarsden** [comment]
Hi Howard - did you hear back from Urkund on this one?

**Comment by thepurpleblob** [comment]
No we didn't. It's been hard getting a straight answer about these issues. Having said that, it all seems to have settled down now, so I think we can forget it unless anything strange starts happening again

**Comment by danmarsden** [comment]
cool - I'll close this off for now but let me know if we need to look at it again. Thanks!
