### ISSUE TITLE
'Error' submissions show complete XML envelope to the student

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#81]
When a file is in 'Error' condition and the student mouses over the warning icon, they now see the complete XML envelope. It's not the end of the world or insecure but it looks a bit messy. 

To be honest, I'm not even sure that they know to mouse over the icon ;-)

**Comment by danmarsden** [comment]
it's a "feature" ;-) 

- I'll remove it next time I'm working on it - thanks.

**Comment by thepurpleblob** [comment]
I'm not saying that having that stuff logged isn't useful. I'm just not sure it helps the students :-P

**Comment by jpahullo** [comment]
Yes, we have the same issue:

![urkund_error](https://user-images.githubusercontent.com/2048296/32165069-d968c856-bd61-11e7-9924-a6ebaebcd189.png)

It is not so convenient nor clear to the final user the error. 

It would be more compelling stating that that file cannot be processed. It would be also interesting to retain the whole error information: Moodle administrators could use this full error information to debug or understand what happened.

I mean, my proposal is the following:

* maybe the text shown on the title could be a generic error message or according to the error code included in the XML content. 
* And then, the same users or only for administrators to get the whole error message via an additional link or so (like with a text like `Error detail` or similar, beside the alert icon).

Thank you so much!

**Comment by danmarsden** [comment]
yeah - definitely room for some improvement there - it's come up a few times in the last couple of months. in some cases we should probably parse that xml and show the "Message" content but it won't always be xml and I left it in place to help admins to diagnose stuff.... but it probably shouldn't dump the whole lot when students are viewing it.

feel free to submit a pull request to help improve it - otherwise urkund might get me to improve it at some point. Thanks.

**Comment by jpahullo** [comment]
Thank you so much for your feedback. It is very kind from you.

We will consider your words.

Regards,

Jordi

**Comment by danmarsden** [comment]
Murdoch had a patch to convert the wordcount to a charcount which also tidied up this error reporting which is now in the master branch here, so I'm flagging this as done - it does mean the full xml envelope will only be viewable in the db, but I think that is correct behaviour. Thanks!
