### ISSUE TITLE
Resubmit timed out issues

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#82]
If an issue reaches 'time out' (too many attempts) and is still in state '202' then we think it would be a good idea to resubmit it (i.e. start again). 

We are seeing a very small percentage of submissions simply getting 'lost' in this manner and this might help. 

We also think that the maximum tries (which we think is around 2.5days) is a bit too long. We don't have a definite statement from Urkund of when 'give up' time is but over 2 days seems rather a lot. If it doesn't come back within a small number of hours it isn't coming back ;-)

**Comment by danmarsden** [comment]
I'm not sure what you're actually asking here....... it's already in a resubmit cycle, what's the point in restarting the cycle again after 2.5 days?  - we need to stop trying "at some point" - 2(2.5) days is the time frame URKUND asked as the upper limit - I guess that also allows them to take the server out for 24 hours for unexpected maintenance tasks?

**Comment by thepurpleblob** [comment]
Unless I've got the wrong end of this... I mean that rather than going to 'Error' state (when timing out) the plugin simply tries to send the file to urkund again. That is, completely give up the attempt and start again. 

Yes, I agree, this is caused by a problem at Urkund's end, but experience suggests that a small number of submissions do get lost in their system. We would propose that there is no point giving up on a submission just send it again.

**Comment by danmarsden** [comment]
so - you're asking for the time-out to be removed completely and submit the file indefinitely? - I don't like that idea very much to be honest.

**Comment by thepurpleblob** [comment]
Yeh - I can understand why not. Urkund really need to fix the issue, rather than papering over it. 

I'm just putting it out there. It really *shouldn't* time out once you've got a 202 and then waited days so I suppose I wondered if you had a more elegant answer.

**Comment by danmarsden** [comment]
I guess we could look at increasing the timeout values, but the current value is one set as requested by Urkund so I'll need to close this as "won't fix" - unless you get more information from Urkund or convince them that the timeout levels are too low.

**Comment by danmarsden** [comment]
closing this one as won't fix - the values are set as requested by Urkund, we shouldn't make them submit indefinitely so they should time-out at some point. If you think the time-out values are not ideal - fire that feedback directly through to Urkund and ask them to add this to think about this in future development.
