### ISSUE TITLE
Error in urkund / Blocking event queue in moodle 2.8.3

### ISSUE THREAD

**Issue by neeesn** [danmarsden/moodle-plagiarism_urkund#84]
Hi Dan 

We have some issues regarding the events that is blockin urkund queue.
We can delete the error in the table mdl_events_queue_handlers

The error we get from the table is: 

Handler function of component plagiarism_urkund: s:26:"urkund_event_file_uploaded"; threw exception :Error reading from database
 * line 1080 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
 * line 1305 of /lib/dml/moodle_database.php: call to mysqli_native_moodle_database->get_records_sql()
 * line 624 of /plagiarism/urkund/lib.php: call to moodle_database->get_records_select()
 * line 741 of /plagiarism/urkund/lib.php: call to plagiarism_plugin_urkund->event_handler()
 * line ? of unknownfile: call to urkund_event_file_uploaded()
 * line 299 of /lib/eventslib.php: call to call_user_func()
 * line 343 of /lib/eventslib.php: call to events_dispatch()
 * line 450 of /lib/eventslib.php: call to events_process_queued_handler()
 * line 45 of /lib/classes/task/events_cron_task.php: call to events_cron()
 * line 74 of /lib/cronlib.php: call to core\task\events_cron_task->execute()
 * line 61 of /admin/cli/cron.php: call to cron_run()
 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')  ORDER BY id' at line 1
 SELECT * FROM mdl_plagiarism_urkund_files WHERE cm = ? AND userid IN ()  ORDER BY id
 [array (
   0 => '61473',
 )]

In the debugging tab of the plugin we get error:
 stdClass Object
(
    [id] => 93473
    [status] => 1
    [timemodified] => 1456390780
    [eventdata] => stdClass Object
        (
            [modulename] => assign
            [cmid] => 61615
            [itemid] => 51365
            [courseid] => 1731
            [userid] => 2907
            [files] => Array
                (
                    [07124240ba54672e42732cb9f7cc80a591d4b85d] => stored_file Object
                        (
                            [fs:stored_file:private] => file_storage Object
                                (
                                    [filedir:file_storage:private] => /data/moodledata/moodle.kvuc.dk/moodledata/filedir
                                    [trashdir:file_storage:private] => /data/moodledata/moodle.kvuc.dk/moodledata/trashdir
                                    [tempdir:file_storage:private] => /data/moodledata/moodle.kvuc.dk/moodledata/temp/filestorage
                                    [dirpermissions:file_storage:private] => 511
                                    [filepermissions:file_storage:private] => 438
                                )

                            [file_record:stored_file:private] => stdClass Object
                                (
                                    [id] => 828689
                                    [contenthash] => 7eeccb9418a962b304a5632720d0eb43feac7ce7
                                    [pathnamehash] => 07124240ba54672e42732cb9f7cc80a591d4b85d
                                    [contextid] => 100691
                                    [component] => assignsubmission_file
                                    [filearea] => submission_files
                                    [itemid] => 51365
                                    [filepath] => /
                                    [filename] => Danielle Nissen.odp
                                    [userid] => 2151
                                    [filesize] => 3843204
                                    [mimetype] => application/vnd.oasis.opendocument.presentation
                                    [status] => 0
                                    [source] => Skal vi sulte I 2050.odp
                                    [author] => Danielle Nissen
                                    [license] => allrightsreserved
                                    [timecreated] => 1455261860
                                    [timemodified] => 1455261864
                                    [sortorder] => 0
                                    [referencefileid] => 
                                    [repositoryid] => 
                                    [reference] => 
                                    [referencelastsync] => 
                                )

                            [filedir:stored_file:private] => /data/moodledata/moodle.kvuc.dk/moodledata/filedir
                            [repository:stored_file:private] => 
                        )

                    [758825e7888af38ff5278327ba2d52e3b02fefd7] => stored_file Object
                        (
                            [fs:stored_file:private] => file_storage Object
                                (
                                    [filedir:file_storage:private] => /data/moodledata/moodle.kvuc.dk/moodledata/filedir
                                    [trashdir:file_storage:private] => /data/moodledata/moodle.kvuc.dk/moodledata/trashdir
                                    [tempdir:file_storage:private] => /data/moodledata/moodle.kvuc.dk/moodledata/temp/filestorage
                                    [dirpermissions:file_storage:private] => 511
                                    [filepermissions:file_storage:private] => 438
                                )

                            [file_record:stored_file:private] => stdClass Object
                                (
                                    [id] => 828707
                                    [contenthash] => c5cea1b92b920a94c524232a88da8c1cd0428419
                                    [pathnamehash] => 758825e7888af38ff5278327ba2d52e3b02fefd7
                                    [contextid] => 100691
                                    [component] => assignsubmission_file
                                    [filearea] => submission_files
                                    [itemid] => 51365
                                    [filepath] => /
                                    [filename] => Præsentation Geo.pptx
                                    [userid] => 2907
                                    [filesize] => 2796597
                                    [mimetype] => application/vnd.openxmlformats-officedocument.presentationml.presentation
                                    [status] => 0
                                    [source] => Præsentation Geo.pptx
                                    [author] => Stine Johansen
                                    [license] => allrightsreserved
                                    [timecreated] => 1455262029
                                    [timemodified] => 1455262036
                                    [sortorder] => 0
                                    [referencefileid] => 
                                    [repositoryid] => 
                                    [reference] => 
                                    [referencelastsync] => 
                                )

                            [filedir:stored_file:private] => /data/moodledata/moodle.kvuc.dk/moodledata/filedir
                            [repository:stored_file:private] => 
                        )

                )

            [file] => Array
                (
                    [07124240ba54672e42732cb9f7cc80a591d4b85d] => stored_file Object
                        (
                            [fs:stored_file:private] => file_storage Object
                                (
                                    [filedir:file_storage:private] => /data/moodledata/moodle.kvuc.dk/moodledata/filedir
                                    [trashdir:file_storage:private] => /data/moodledata/moodle.kvuc.dk/moodledata/trashdir
                                    [tempdir:file_storage:private] => /data/moodledata/moodle.kvuc.dk/moodledata/temp/filestorage
                                    [dirpermissions:file_storage:private] => 511
                                    [filepermissions:file_storage:private] => 438
                                )

                            [file_record:stored_file:private] => stdClass Object
                                (
                                    [id] => 828689
                                    [contenthash] => 7eeccb9418a962b304a5632720d0eb43feac7ce7
                                    [pathnamehash] => 07124240ba54672e42732cb9f7cc80a591d4b85d
                                    [contextid] => 100691
                                    [component] => assignsubmission_file
                                    [filearea] => submission_files
                                    [itemid] => 51365
                                    [filepath] => /
                                    [filename] => Danielle Nissen.odp
                                    [userid] => 2151
                                    [filesize] => 3843204
                                    [mimetype] => application/vnd.oasis.opendocument.presentation
                                    [status] => 0
                                    [source] => Skal vi sulte I 2050.odp
                                    [author] => Danielle Nissen
                                    [license] => allrightsreserved
                                    [timecreated] => 1455261860
                                    [timemodified] => 1455261864
                                    [sortorder] => 0
                                    [referencefileid] => 
                                    [repositoryid] => 
                                    [reference] => 
                                    [referencelastsync] => 
                                )

                            [filedir:stored_file:private] => /data/moodledata/moodle.kvuc.dk/moodledata/filedir
                            [repository:stored_file:private] => 
                        )

                    [758825e7888af38ff5278327ba2d52e3b02fefd7] => stored_file Object
                        (
                            [fs:stored_file:private] => file_storage Object
                                (
                                    [filedir:file_storage:private] => /data/moodledata/moodle.kvuc.dk/moodledata/filedir
                                    [trashdir:file_storage:private] => /data/moodledata/moodle.kvuc.dk/moodledata/trashdir
                                    [tempdir:file_storage:private] => /data/moodledata/moodle.kvuc.dk/moodledata/temp/filestorage
                                    [dirpermissions:file_storage:private] => 511
                                    [filepermissions:file_storage:private] => 438
                                )

                            [file_record:stored_file:private] => stdClass Object
                                (
                                    [id] => 828707
                                    [contenthash] => c5cea1b92b920a94c524232a88da8c1cd0428419
                                    [pathnamehash] => 758825e7888af38ff5278327ba2d52e3b02fefd7
                                    [contextid] => 100691
                                    [component] => assignsubmission_file
                                    [filearea] => submission_files
                                    [itemid] => 51365
                                    [filepath] => /
                                    [filename] => Præsentation Geo.pptx
                                    [userid] => 2907
                                    [filesize] => 2796597
                                    [mimetype] => application/vnd.openxmlformats-officedocument.presentationml.presentation
                                    [status] => 0
                                    [source] => Præsentation Geo.pptx
                                    [author] => Stine Johansen
                                    [license] => allrightsreserved
                                    [timecreated] => 1455262029
                                    [timemodified] => 1455262036
                                    [sortorder] => 0
                                    [referencefileid] => 
                                    [repositoryid] => 
                                    [reference] => 
                                    [referencelastsync] => 
                                )

                            [filedir:stored_file:private] => /data/moodledata/moodle.kvuc.dk/moodledata/filedir
                            [repository:stored_file:private] => 
                        )

                )

            [pathnamehashes] => Array
                (
                    [0] => 07124240ba54672e42732cb9f7cc80a591d4b85d
                    [1] => 758825e7888af38ff5278327ba2d52e3b02fefd7
                )

        )

    [stackdump] => 
    [userid] => 2907
    [eventname] => assessable_file_uploaded
    [component] => plagiarism_urkund
    [handlerfile] => /plagiarism/urkund/lib.php
    [handlerfunction] => s:26:"urkund_event_file_uploaded";
)

We have run into this error multiple times and different sites, it helps deleting it directly in the DB, but there can be many errors like this in a queue with 3000 entries. The queue wont move as long as the error is there, so there is no other option than deliting directly in the database.
http://screencast.com/t/ukFEViwM8xe

**Comment by danmarsden** [comment]
Sounds like you are using an old version of the plugin. You should upgrade to the latest version.
