### ISSUE TITLE
'found more than one record' notices (Moodle 3.1)

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#85]
We've been testing on Moodle 3.1 (you may not fully support it yet, but...) and have been seeing these on the Assignment grading page...

Error: mdb->get_record() found more than one record!
line 1539 of /lib/dml/moodle_database.php: call to debugging()
line 318 of /plagiarism/urkund/lib.php: call to moodle_database->get_record_sql()
line 158 of /plagiarism/urkund/lib.php: call to plagiarism_plugin_urkund->get_file_results()
line 51 of /lib/plagiarismlib.php: call to plagiarism_plugin_urkund->get_links()
line 1405 of /mod/assign/renderer.php: call to plagiarism_get_links()
line 63 of /mod/assign/renderer.php: call to mod_assign_renderer->htmllize_tree()
line 319 of /lib/outputrenderers.php: call to mod_assign_renderer->render_assign_files()
line 50 of /mod/assign/renderer.php: call to plugin_renderer_base->render()
line 5144 of /mod/assign/locallib.php: call to mod_assign_renderer->assign_files()
line 327 of /mod/assign/submission/file/locallib.php: call to assign->render_area_files()
line 1207 of /mod/assign/gradingtable.php: call to assign_submission_file->view_summary()
line 1291 of /mod/assign/gradingtable.php: call to assign_grading_table->format_plugin_summary_with_link()
line 812 of /lib/tablelib.php: call to assign_grading_table->other_cols()
line 456 of /mod/assign/gradingtable.php: call to flexible_table->format_row()
line 1493 of /lib/tablelib.php: call to assign_grading_table->format_row()
line 1609 of /lib/tablelib.php: call to table_sql->build_table()
line 1439 of /mod/assign/renderer.php: call to table_sql->out()
line 1235 of /mod/assign/renderer.php: call to mod_assign_renderer->flexible_table()
line 319 of /lib/outputrenderers.php: call to mod_assign_renderer->render_assign_grading_table()
line 3771 of /mod/assign/locallib.php: call to plugin_renderer_base->render()
line 3856 of /mod/assign/locallib.php: call to assign->view_grading_table()
line 572 of /mod/assign/locallib.php: call to assign->view_grading_page()
line 52 of /mod/assign/view.php: call to assign->view()

**Comment by thepurpleblob** [comment]
It appears to be if different students submit a document with exactly the same name. Which is quite likely if they have been given a title for the work

**Comment by danmarsden** [comment]
Thanks Howard - I've done some initial testing with 3.1 but hadn't noticed that, I'll track it down and patch it.

**Comment by danmarsden** [comment]
found it - looks like in 3.1 when a file is uploaded on behalf the ownership of the file remains with the uploader (teacher) we were checking that during the post to urkund and modifying the record assuming that it was incorrect. We don't need to do that anymore because we look at relateduserid in the actual event when creating the record. I've updated the plugins db with the new version too. Thanks for letting me know! 

Note: that won't fix existing records in an incorrect state, but hopefully it's just a test environment for you so won't matter too much.
