### ISSUE TITLE
Have the retry timings been changed

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#89]
Time now is 14:12... here is a snippet from the Debug page...

![screen shot 2016-07-25 at 14 11 00](https://cloud.githubusercontent.com/assets/664139/17102579/32ad56f4-5272-11e6-957d-6e3932738d75.png)

...and the Scheduled tasks page...

![screen shot 2016-07-25 at 14 12 01](https://cloud.githubusercontent.com/assets/664139/17102587/3d9425c0-5272-11e6-804e-098e298eb8b1.png)

In something over two hours I would have expected more than 1 retry for a score. This seems to be since we (finally) upgraded to the latest version of the plugin last week.

**Comment by danmarsden** [comment]
did you use the reset-all button? - it resets the attempt count back to "1" - (on your request!) :-)

**Comment by thepurpleblob** [comment]
*I* didn't. However, someone else might have done. I'll go and make enquiries ;-)

**Comment by danmarsden** [comment]
presume this one can be closed - let me know if we need to take another look at this.

**Comment by universityofglasgow** [comment]
Yep - think this was me and a colleague trying to confuse each other (and succeeding!!)
