### ISSUE TITLE
Timed out error

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#91]
We've been getting quite a few of these....

```
mysql> select * from mdl_plagiarism_urkund_files where cm=348902 and userid=81164\G
*************************** 1. row ***************************
             id: 142040
             cm: 348902
         userid: 81164
  relateduserid: NULL
     identifier: 795775061b54af5d645867f444d453e4c7512d46
       filename: MachiavelliEssay.pdf
      reporturl: NULL
         optout: NULL
     statuscode: 613
similarityscore: 0
        attempt: 0
  errorresponse: connect() timed out!
  timesubmitted: 1477231874
1 row in set (0.00 sec)
```

I don't recall seeing this before. If Urkund servers are not responding why is the plugin giving up without retrying?

By using 'reset' it goes fine but staff like to moan...

**Comment by danmarsden** [comment]
thanks - it looks like that particular error state isn't automatically resubmitted. I'll take a look and implement some form of handler.

**Comment by danmarsden** [comment]
I've just pushed a patch through into the master branch that should address this but I haven't had a chance to test it properly - any chance you could help with that?
