### ISSUE TITLE
Finding submissions that do not appear in grading table

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#93]
Example...

```
mysql> select id,identifier,userid, relateduserid, filename,reporturl,statuscode,similarityscore,attempt from mdl_plagiarism_urkund_files where id=164959\G
*************************** 1. row ***************************
             id: 164959
     identifier: 16743b40d984200716b1097b649ae4451fecb5c0
         userid: 33840
  relateduserid: 77496
       filename: 2243726S.docx
      reporturl: https://secure.urkund.com/view/22993875-896146-911636
     statuscode: Analyzed
similarityscore: 8
        attempt: 2
1 row in set (0.00 sec)
```

However, when you look at the assignment in Moodle...

![screen shot 2016-11-17 at 15 04 00](https://cloud.githubusercontent.com/assets/664139/20394369/2b11ce60-acd7-11e6-982b-e81a12f618f0.png)

Nothing at all for that user (the user can't see their score either). I appreciate that this is a submitted on behalf of entry which probably has something to do with it. 

As this is our live system, it's very difficult (well, impossible) to debug the thing.

**Comment by danmarsden** [comment]
The first thing I'd check would be to see if the contenthash of the current submission matches the contenthash in the db - If they don't match it would suggest the file was updated and it didn't trigger a new submission to Urkund. If they do match it suggests a bug with the way it grabs the record from the db to show the report.

**Comment by danmarsden** [comment]
I reproduced this specific issue and found a fix which I've added (where relateduserid <> userid - and the submission was made on-behalf.) - will leave the other issue open as you suggest it occurred in a normal submission as well?
